### ISSUE TITLE
fsevents needs OS X (darwin)

### ISSUE THREAD

**Issue by Leetcore** [OfficeDev/PnP-JS-Core#104]
npm install is failing because of fsevents on Windows and Linux. 

####Steps to Reproduce
clone repo
npm install
Try on Windows/Linux

npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12

I hope it will work on more OS if its ready.

Best regards!

**Comment by derek-smith** [comment]
Everything is fine. npm is saying that your machine doesn't need fsevents to work. Read the line above that one too:

`npm WARN optional Skipping failed optional dependency /chokidar/fsevents:`
`npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12`

If you needed that dependency, it should get installed too.

**Comment by Leetcore** [comment]
Yes, this was the warning before the error.

npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN prefer global marked@0.3.5 should be installed with -g

> sp-pnp-js@0.0.11 postinstall C:\Users\User\PnP-JS-Core
> typings install

Der Befehl "typings" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.7
npm ERR! code ELIFECYCLE
npm ERR! sp-pnp-js@0.0.11 postinstall: `typings install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sp-pnp-js@0.0.11 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sp-pnp-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sp-pnp-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sp-pnp-js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\User\PnP-JS-Core\npm-debug.log

**Comment by Leetcore** [comment]
My colleague can install it. It should be a local problem.
