### ISSUE TITLE
Bug in pnp.d.ts from npmjs.com/sp-pnp-js

### ISSUE THREAD

**Issue by searus** [OfficeDev/PnP-JS-Core#116]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Expected / Desired Behavior / Question
Compiling typescript using the pnp.d.ts definition file in npmjs.com/sp-pnp-js

#### Observed Behavior
Compile fails with the error: (3365,5): A 'declare' modifier cannot be used in an already ambient context.

#### Steps to Reproduce
Compile any typescript against this definition file.

**Comment by patrick-rodgers** [comment]
Thanks @searus, fixed in PR #120 and in the dev branch. NPM package will be updated next time we merge to master (likely tomorrow or Friday).
