### ISSUE TITLE
loadStylesheet from utils not working

### ISSUE THREAD

**Issue by Djemel** [OfficeDev/PnP-JS-Core#124]
#### Category
[ ] Enhancement

[ X] Bug

[ ] Question

#### Expected / Desired Behavior / Question
Stylesheet should be added to "head"

#### Observed Behavior
Stylesheed not added to "head"

#### Steps to Reproduce
call pnp.utils.loadStylesheet('_path_to_my_stylesheet_', false);

The issue seems to come from this test:
if (head.length > 1)
should be either head.length > 0 or >= 1

**Comment by patrick-rodgers** [comment]
Thanks, will take a look

**Comment by olemp** [comment]
Why not use registerCssLink? What's the pros of using this vs registerCssLink?

**Comment by patrick-rodgers** [comment]
Correct, it was originally in the code from which these utility functions are derived because it was easier to have a few lines in a method then to always rely on the SP.* libraries being present.

**Comment by patrick-rodgers** [comment]
This is now fixed in dev branch, will merge to main shortly for a patch release.
