### ISSUE TITLE
Unexpected token in JSON error

### ISSUE THREAD

**Issue by Akhoy** [OfficeDev/PnP-JS-Core#125]
#### Category

Bug

#### Expected / Desired Behavior / Question
Display title of the current site.

#### Observed Behavior

> SyntaxError: Unexpected token < in JSON at position 0 at ODataDefaultParser.ODataParserBase.parse 

#### Steps to Reproduce
I am using the following code as I got from [Wiki](https://github.com/OfficeDev/PnP-JS-Core/wiki/Install-and-Use) in a content editor web part on an on-premise version of SharePoint 2013.
`$pnp.sp.web.select("Title").get()
.then(function(data){
console.log(data.title);
})
.catch(function(data){
console.log(data);
});`
I am getting the above error in the console when I run this. I've downloaded pnp.js and referred it in the HTML. I'm using Chrome. Any help?

**Comment by patrick-rodgers** [comment]
This is due to the metadata not being on by default in SharePoint 2013 SP1 as discussed [here](https://technet.microsoft.com/en-us/library/dn762092(v=office.15).aspx). This has been raised by a few folks so we are looking at how to address it. Thanks for logging it.

**Comment by Akhoy** [comment]
Didn't know about this feature. Will enable it and use this as a workaround till the bug is fixed.Thanks!

**Comment by patrick-rodgers** [comment]
I have a fix for this in PR #127 - any chance you can pull that PR branch and do a test on-prem for me?

**Comment by Akhoy** [comment]
OK. I'll check it out and let you know. Pls let me know the steps for that. Quite a beginner with git.

**Comment by patrick-rodgers** [comment]
I was able to test it, the fix is good, will merge the PR.

**Comment by patrick-rodgers** [comment]
This is now fixed in dev branch, will merge to main shortly for a patch release.

**Comment by PatrickUMAknow** [comment]
Hello Patrick,
Just got the exact same error while testing PnP for the first time (https://github.com/SharePoint/PnP-JS-Core/wiki/Getting-Started:-Install-&-Use#from-a-content-editor-webpart)
My environment is on-premises and I can't use the suggested workaround (I'm site coll. admin with no access to servers).
I'm using pnp.js 2.0.0. Is it the latest release ? (I'm new to github so I'm not sure I'm getting the latest version). I guess your correction should be included.
Thanks for the help
Patrick B.
