### ISSUE TITLE
Erros while using PnP-JS-Core Typescript files.

### ISSUE THREAD

**Issue by aseemone** [OfficeDev/PnP-JS-Core#126]
#### Category
Bug

#### Expected / Desired Behavior / Question
_Should be able to resolve and compile the TypeScript definitions without complaining about duplicates_

#### Observed Behavior
There are multiple "Duplicate identifier XXX" errors after adding the TypeScript error. on changing few settings, at times it complains about the "Cannot find name XXX" as well.

#### Steps to Reproduce
Steps to reproduce the issue
- create a new SharePoint Add-In (SharePoint hosted) project
- add a new module "node_modules" and get rid of the sample.txt file
- open console and navigate to node_modules 
- run the npm command: npm install sp-pnp-js --save dev
- you get the Duplicate error, screenshots attached

![ts error screenshot](https://cloud.githubusercontent.com/assets/17793735/15945726/aec9d828-2e48-11e6-90e7-c5322af91f15.png)

**Comment by patrick-rodgers** [comment]
Thanks, will work on getting this resolved.

**Comment by patrick-rodgers** [comment]
This is now fixed in dev branch, will merge to main shortly for a patch release.
