### ISSUE TITLE
Allow per call overrides for the options set in the .setup function

### ISSUE THREAD

**Issue by sympmarc** [OfficeDev/PnP-JS-Core#134]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[X] Enhancement

[ ] Bug

[ ] Question

#### Expected / Desired Behavior / Question
It's great to set options up front that are applied consistently, and many times it is perfect. But there are times, especially during development, where you want to pass specific values. For instance, odata=verbose in one call only. suggest you allow per call overrides to the .setup function.

I think this will become more and more important as the capabilities of the .setup function expand.

**Comment by patrick-rodgers** [comment]
Have a look at #136 which now supports ability to set headers and other fetch params on a per-call basis. Also introduces cachine on a per-call basis, composable with batching, and global disable-able for dev scenarios.

**Comment by sympmarc** [comment]
Without trying it out, what you show in #136 seems like the right way to go.

**Comment by patrick-rodgers** [comment]
This was merged in as part of #136 today, closing issue. We can track future enhancements on others issues. Thanks for logging this!
