### ISSUE TITLE
Tracking issue for gulp-header bug

### ISSUE THREAD

**Issue by mike-morrison** [OfficeDev/PnP-JS-Core#138]
#### Category
- [ ] Enhancement

- [x] Bug

- [ ] Question

#### Observed Behavior
npm install fails with error about a missing file.  Already fixed in #137 

This is just a tracking issue so we can go back to installing the latest gulp-header after [this PR](https://github.com/tracker1/gulp-header/pull/38) is merged and a later version is added to NPM.

**Comment by patrick-rodgers** [comment]
Closing as per #172 fix. Thanks Mike!
