### ISSUE TITLE
Licensing information for distributed files

### ISSUE THREAD

**Issue by Danny-Engelman** [OfficeDev/PnP-JS-Core#146]
#### Category
[ x ] Enhancement

[ ] Bug

[ x ] Question

#### Question
/dist/pnp.js contains a very minimal copyright notice, and has the Microsoft (c) first

```
/**
 * sp-pnp-js v1.0.1 - A reusable JavaScript library targeting SharePoint client-side development.
 * Copyright (c) 2016 Microsoft
 * MIT
 */

```
quote from: https://www.gnu.org/licenses/license-list.en.html

> **...the MIT license, [..] is misleading, since MIT has used many licenses for software**.

if you only download pnp.js and never look at the correct LICENSE file in the root it is unclear what the license grants. That's why I reacted so harsh, I only looked at pnp.js

Since pnp.js will be distributed and shared as a single file, users might never browse to GitHub

General consensus  is each file (distributed as separate file) should include the whole license:
references:
* https://www.gnu.org/licenses/license-list.en.html
* http://www.gnu.org/licenses/gpl-2.0.html#SEC4
* http://programmers.stackexchange.com/questions/125836/do-you-have-to-include-a-license-notice-with-every-source-file

#### Proposed change to built:
* Include title:  
**pnp.js [version]  
generated from the Typescript sources at: https://github.com/OfficeDev/PnP-JS-Core**  
**for documentation refer to: http://dev.office.com/patterns-and-practices**  

* Include the LICENSE file from the root, not a separate text in a built proces
* optional, no legal requirement, include AUTHORS

**Comment by patrick-rodgers** [comment]
I am good with these changes, as I said in the other thread as well. I do not think we need to include the authors file contents. We'll likely look to get 1.0.3 out the door in the next few weeks but no firm date currently. If you can get a PR together we can include in then. Thanks

**Comment by mike-morrison** [comment]
@patrick-rodgers If I understood the above, we would be taking the entire license file and adding it to the output.  I think we should stick to being inline with what other Microsoft projects are following.  I have never seen any of our other projects include the entire license.  I do like the idea of including a link to the documentation and the license file as a nice value add to people.  Just my thoughts.

**Comment by patrick-rodgers** [comment]
I updated the header and am closing this issue.
