### ISSUE TITLE
Firefox throws error on using PnP.js file

### ISSUE THREAD

**Issue by sksnips** [OfficeDev/PnP-JS-Core#151]
#### Category
[ ] Enhancement

[ X] Bug

[X ] Question

#### Expected / Desired Behavior / Question
PnP.js file not working with firefox. is it a known issue?

#### Observed Behavior
Using the PnP.js file returns the following error when accessing in Mozilla Firefox,

**TypeError: 'headers' member of RequestInit could not be converted to any of: Headers, ByteStringSequenceSequence, ByteStringMozMap.**

#### Steps to Reproduce
Add a below code to Script editor/ content editor webpart

```
<script type="text/javascript" src="/siteassets/scripts/pnp.min.js"></script> 
<script type="text/javascript" src="/siteassets/scripts/fetch.js"></script> 
<script type="text/javascript" src="/siteassets/scripts/es6-promise.js"></script>

<script type="text/javascript">
$pnp.sp.web.webs.get().then(function(result) {
			console.log(result);
		});
</script>
```

We will get that header issue!
Thanks!

**Comment by patrick-rodgers** [comment]
Thanks for reporting this. Fixed and merged into the dev branch in PR #153. Fix was to add a null check before merging the headers, appears Firefox doesn't like null values for headers.
