### ISSUE TITLE
Get Owner Profile URL 

### ISSUE THREAD

**Issue by lousimonetti** [OfficeDev/PnP-JS-Core#157]
#### Category
[ ] Enhancement

[x] Bug

[x] Question

#### Expected / Desired Behavior / Question
Found a possible issue with line [https://github.com/OfficeDev/PnP-JS-Core/blob/master/src/sharepoint/rest/userprofiles.ts#L243](https://github.com/OfficeDev/PnP-JS-Core/blob/master/src/sharepoint/rest/userprofiles.ts#L243)  

`let q = this.getParent(ProfileLoader, this.parentUrl, "sp.userprofiles.profileloader.getowneruserprofile");`

That endpoint never seems to resolve for me, and just curious if this was supposed to be: 
`let q = this.getParent(ProfileLoader, this.parentUrl, "_api/sp.userprofiles.profileloader.getowneruserprofile");`

I didn't want to change it, without validating that is the intended URL. 

Thanks!

**Comment by patrick-rodgers** [comment]
Yep, looks like a bug to me. Thanks for reporting it, I'm working on and testing a fix.

**Comment by patrick-rodgers** [comment]
Fixed in dev, closing issue. Thanks again for reporting it and providing enough details to make it easy to find and fix!

**Comment by lousimonetti** [comment]
Awesome, glad I could help.
