### ISSUE TITLE
More detail information about SharePoint Add-in registration

### ISSUE THREAD

**Issue by mauricionr** [OfficeDev/PnP-JS-Core#158]
#### Category
[ ] Enhancement

[ ] Bug

[X ] Question

![image](https://cloud.githubusercontent.com/assets/2263551/16933731/9bca723a-4d26-11e6-9c1d-0c83a0282a9d.png)

I've started make questions in this PR #156 and i got more question so i decide to create this Issue,

I'm trying to follow the steps on wiki to register my app in AppInv.aspx

In AppInv.aspx registration i must fill the *Permission Request XML*

How is the pattern to add this *Permission Request XML*

On [Retrieve add-in registration and add-in principal information](https://msdn.microsoft.com/en-us/library/office/jj687469.aspx#Anchor_3) is missing this info

Will be nice if we have a clearly documentation about Add-ins

Thanks and sorry my English 😄

**Comment by mike-morrison** [comment]
````
<AppPermissionRequests>
    <AppPermissionRequest Scope="http://sharepoint/content/sitecollection/web/list" Right="Write"/>
  </AppPermissionRequests>
````

See [this page](https://msdn.microsoft.com/en-us/library/office/fp142383.aspx) for the options that can be specified.

This is fairly new functionality.  Apologies for the rough edges.  Thank you for the feedback, please keep it coming.

**Comment by mauricionr** [comment]
@mike-morrison really thanks in advance, i will check it out!

😄

**Comment by patrick-rodgers** [comment]
```
  <AppPermissionRequests AllowAppOnlyPolicy="true">
    <AppPermissionRequest Scope="http://sharepoint/content/sitecollection" Right="FullControl" />
    <AppPermissionRequest Scope="http://sharepoint/social/tenant" Right="FullControl" />
    <AppPermissionRequest Scope="http://sharepoint/search" Right="QueryAsUserIgnoreAppPrincipal" />
  </AppPermissionRequests>
```

That is the full XML I am currently using for testing. May need to add to it in the future but so far that covers all the bases. We need a wiki article on setting up for testing, I've added it to my list. Thanks @mauricionr.

**Comment by patrick-rodgers** [comment]
Added a [new wiki article](https://github.com/OfficeDev/PnP-JS-Core/wiki/Testing-Against-SharePoint) on getting setup for testing.

**Comment by patrick-rodgers** [comment]
Does that provide enough information such that we can close the ticket? We can always up the article in the future.

**Comment by mauricionr** [comment]
Yes @patrick-rodgers,

really thanks in advance!

I've alredy register an app and grant the permissions to them, now let's test :smile: !

Thanks again!

**Comment by mauricionr** [comment]
Hey @patrick-rodgers my first app i've registered with mike XML,

Now i'm trying to register with your XML

I'm getting this message

**The tenant administrator must approve this application.**

![image](https://cloud.githubusercontent.com/assets/2263551/17037170/f37c8036-4f65-11e6-9e28-303b91eda566.png)

![image](https://cloud.githubusercontent.com/assets/2263551/17037187/0878416e-4f66-11e6-928f-79daaa1a737b.png)

Any ideia?

Thanks!

**Comment by mauricionr** [comment]
I guess this information could be placed at [Testing-Against-SharePoint](https://github.com/OfficeDev/PnP-JS-Core/wiki/Testing-Against-SharePoint)

**Comment by mike-morrison** [comment]
You need to be a tenant admin to apply those permissions or you need a tenant admin to do it for you.  Otherwise you need to remove all of the tenant scoped permission requests.  I think the assumption was that developers would be running a dev or trial tenant.

**Comment by mauricionr** [comment]
I'm Principal Administrator Site Collection of three sites

company.sharepoint.com
company.sharepoint.com/search
company-my.sharepoint.com

This is considered tenant admin?

Thanks again!! :smile:

**Comment by patrick-rodgers** [comment]
I added a line to the article stating this. Unfortunately there isn’t a way around this requirement. You can use the free option, use a developer account tied to an MSDN subscription, or purchase a developer account.

**Comment by mauricionr** [comment]
I'm trying to discovery if i'm a tenant admin with powershell, but i guess i'm.

I've alredy have paied sharepoint online it's not necessary free option or developer account in my case!

Thanks @patrick-rodgers !

**Comment by mauricionr** [comment]
I've created another dev site to test but the same error :cry: 

![image](https://cloud.githubusercontent.com/assets/2263551/17062674/4cf3c328-500a-11e6-9339-133a4faa7ac4.png)

**Comment by mauricionr** [comment]
This XML works for me, i could trust in my app, but it not equal to the @patrick-rodgers XML, maybe somehting problem will appear

```XML

 <AppPermissionRequests AllowAppOnlyPolicy="true">
<AppPermissionRequest Scope="http://sharepoint/content/sitecollection" Right="FullControl" />
    <AppPermissionRequest Scope="http://sharepoint/social" Right="FullControl" />
    <AppPermissionRequest Scope="http://sharepoint/content" Right="FullControl"/>
  </AppPermissionRequests>

```

**Comment by mike-morrison** [comment]
@mauricionr Are you using the same account you created the O365 tenant with?  By default the tenant admin is the account you created when going through the initial setup.

**Comment by mauricionr** [comment]
@mike-morrison i request to my boss, 

he tried to aprove the app permissions, 

neither them could aprove the app permissions, 

he created the O365 tenant.

**Comment by mauricionr** [comment]
I'm trying to request permission in another SharePoint Online and i'm getting the same message.

The user i'm using is the tenant administrator, only exist one user in this enviroment.


![image](https://cloud.githubusercontent.com/assets/2263551/17070777/467fccec-5034-11e6-8167-92a087ba1044.png)


![image](https://cloud.githubusercontent.com/assets/2263551/17070676/b688678e-5033-11e6-9d9f-3b69f26b66db.png)

_______

When i remove the `AllowAppOnlyPolicy="true"` it works, any ideia why?

![image](https://cloud.githubusercontent.com/assets/2263551/17070819/6feb538a-5034-11e6-8872-f79b278b398a.png)


![image](https://cloud.githubusercontent.com/assets/2263551/17070853/a0add600-5034-11e6-9cf2-4ecedd8b56c0.png)


Thanks guys!

**Comment by patrick-rodgers** [comment]
Without the app only auth the node client won't work as it only uses app only permissions. Only tenant admins as defined in the tenant settings can approve these permissions. Unfortunately app only is required.

**Comment by mauricionr** [comment]
@patrick-rodgers where i can find this tenant settings?

Both users i've tested were Tenant admin.

**Comment by patrick-rodgers** [comment]
Ok, just learned today that they rolled a change, you can now only grant these permissions in the tenant admin site's appinv page. So something like  https://mytenante-admin.sharepoint.com/_layouts/15/appinv.aspx. Please try the same steps there and let us know if it worked. If so I will update the wiki article.

**Comment by mauricionr** [comment]
@patrick-rodgers now it works, really thanks in advance!

![image](https://cloud.githubusercontent.com/assets/2263551/17147747/76119b3a-533a-11e6-84a7-65a6b7bfb6d3.png)


![image](https://cloud.githubusercontent.com/assets/2263551/17147757/821ff87c-533a-11e6-9e82-f3d2bf88b888.png)

**Comment by mauricionr** [comment]
@patrick-rodgers they could improve the message, the message looks like the *tenant administrator* is a user not a site

**Comment by patrick-rodgers** [comment]
Yes, 100% agree - I just learned about this change this morning and we are having the same conversation internally around messaging and the error message text. So far as I know this hasn't been announced publically yet. So...welcome to the cutting edge :)

**Comment by mauricionr** [comment]
Yay!!!

![image](https://cloud.githubusercontent.com/assets/2263551/17150986/0c05ff66-5348-11e6-9f63-cf06b555216e.png)

**Comment by patrick-rodgers** [comment]
Great - OK to close this issue? I'll add a link to the wiki to the blog post around the new process.

**Comment by mauricionr** [comment]
Ok i'm closing now, really thanks!
