### ISSUE TITLE
Change docs generator

### ISSUE THREAD

**Issue by mauricionr** [OfficeDev/PnP-JS-Core#163]
#### Category
[X ] Enhancement

[ ] Bug

[ X] Question

@patrick-rodgers  I'm researching another docs generator, 

i'm thinking about submit a PR changing the docs gen.

This is pretty good, [@use JSDoc](http://usejsdoc.org/)

Any one knows another one, i will keep my researching?

#147

Thanks!

**Comment by mauricionr** [comment]
This [documentation](https://azure.github.io/azure-mobile-apps-node/) is awsome

![image](https://cloud.githubusercontent.com/assets/2263551/17084071/fb68d03e-518a-11e6-9556-f8d5598ae4d3.png)

![image](https://cloud.githubusercontent.com/assets/2263551/17084065/dfa643ae-518a-11e6-9bd3-6a52f38e87e8.png)

**Comment by tobiaswest83** [comment]
TypeDoc is being used as part of #147, i'm making making progress on this. Not sure there's value in changing implementation to another?

**Comment by jornh** [comment]
I tend to agree with @tobiaswest83 - without having investigated further I'm guessing TypeDoc is the better candidate over jsdoc alone for supporting TypeScript which is the source language for .

And it looks like TypeDoc out-of-the-box is able to generate nice looking docs too, see http://typedoc.io/themes/default/ and http://typedoc.io/themes/minimal/. I'm guessing @patrick-rodgers just started tearing the `default` template apart to be able to build on Office UI Fabric for theming like hinted about in #147 

@tobiaswest83 great to hear that you are making progress. Got anything (even half baked :smile:) you want to share?

Really don't want to step on your toes/duplicate work. "By accident" I ended up looking at two things this weekend:

1. Seeing if I could restore rendering for `@example` tags from the original TypeDoc template resulting  in #162
2. To start learning about UI Fabric (#162 may need to loose the round corners) I toyed with the top banner and responsiveness in 12373df1bac9a8d9d8b426bc4764202b66b043cc  ... I think PnP-JS-Core would benefit from highly visible global nav leading new users in particular into the GH wiki etc ... it's not ready for a PR yet though ...

If nothing else now you know it's there: Steal, get inspired, suggest next steps, or ignore as you see fit - and know that at least I had fun and (re-)learned a bunch about the "new" JS toolchain and UI Fabric. :laughing:

**Comment by tobiaswest83** [comment]
I'll share a Plunk of a work in progress template later using Office UI Fabric controls, I'll check out a comparison of what you've done vs what I've done. Any help is always appreciated, I'm getting married in a month so will be slowing down a bit soon for prep (so I'm told!)

**Comment by jornh** [comment]
Excellent - let's see where this leads

> (so I'm told!)

:smile: - enjoy!

**Comment by mauricionr** [comment]
I was reading both, [TypeDoc](http://typedoc.io/guides/doccomments.html) and [usejsdoc](http://usejsdoc.org/#block-tags).

In my humble opinion, [TypeDoc](http://typedoc.io/guides/doccomments.html) has poor API for generate documents insted of [usejsdoc](http://usejsdoc.org/#block-tags)

[usejsdoc](http://usejsdoc.org/#block-tags) looks like full feature for TypeScript, Javascript/ES5/ES6/ES7

TypeScript and JS/ES6/ES7 it's getting really really closer from each other.

Check out the @johnpapa post about [Understanding ES5, ES2015 and TypeScript](https://johnpapa.net/es5-es2015-typescript/)

And i guess we will not lose any working in progress on the documations.

Thanks for your quick feedback @jornh and @tobiaswest83 :smile:

Congratulations @tobiaswest83 Happy :wedding:

**Comment by jornh** [comment]
@mauricionr initially in this issue you said:

> Any one knows another one, i will keep my researching?
 
As a newcomer here I just saw https://github.com/OfficeDev/PnP-JS-Core/issues/6#issuecomment-210670842 where the topic of "which tool" has been covered before - might interest you :book:

**Comment by mauricionr** [comment]
Really sorry I didn't see this one, I will check out then!

Thanks 😃

**Comment by patrick-rodgers** [comment]
Great discussion folks - we did go with TypeDoc based on @alex-randall's research as well as my trial and error to get things going. I am not wedded to TypeDoc, but it is working so I don't feel a pressure to change. I am more concerned now with getting the documentation formatted nicely, and it is great to see the discussions around that as well. If at some point we need to switch I am open to that, but for now let's stick with TypeDoc and see how that goes. The support for TypeScript was a big selling point as well as the fully customizable template.

**Comment by patrick-rodgers** [comment]
Going to close this as for now at least we will stay with the TypeDoc setup we have. Would like to focus on making the doc UX better, making the docs accessible, and improving the comments. Thanks all for a good discussion.
