### ISSUE TITLE
HttpClient.fetch() method uses new Headers(), which is not supported by IE and Edge browsers

### ISSUE THREAD

**Issue by arheom** [OfficeDev/PnP-JS-Core#167]
#### Category
[ ] Enhancement
[X] Bug
[ ] Question

#### Expected
I was using the following search api to get simple data from SharePoint Search:
_$pnp.sp.search({Querytext: "*"}).then(function (items) {console.log(items);});_
It works as expected in Chrome / Firefox, but in IE / Edge, gets the following error:
_'Headers' is undefined_

#### Observed Behavior
The API does not work in IE / Edge. After researching a bit, looks like the Headers object is not supported by IE or Edge (inside HttpClient.fetch() method):
https://developer.mozilla.org/en-US/docs/Web/API/Headers

#### Steps to Reproduce
1. Open an IE / Edge browser
2. Execute __$pnp.sp.search({Querytext: "*"}).then(function (items) {console.log(items);});_
3. Error will appear.

Thanks!

**Comment by mauricionr** [comment]
@arheom checkout the [polyfill](https://github.com/OfficeDev/PnP-JS-Core/wiki/Install-and-Use#polyfill), are you already using it?

**Comment by arheom** [comment]
you are right! I had them in the solution. removed them later cos I didn't know if are used. added them again and works ;).

**Comment by jornh** [comment]
According to https://blogs.windows.com/msedgedev/2016/05/24/fetch-and-xhr-limitations/ there is support for `fetch()` in *Edge 14*  released as part of the Win 10 "Anniversary Update" this summer. 

So one less browser that needs the polyfill (if you keep Win 10 updated) - still  others needing it. Notably IE and Safari http://caniuse.com/#feat=fetch
