### ISSUE TITLE
Change request url by options

### ISSUE THREAD

**Issue by mauricionr** [OfficeDev/PnP-JS-Core#173]
#### Category
[X ] Enhancement

[ ] Bug

[ ] Question

#### Expected / Desired Behavior / Question
Optional setup the request url in all cases not only in NodeJS implementation

#170 

Thanks!

**Comment by patrick-rodgers** [comment]
You can do this by creating a new Site or Web object with the full url as here:

import { Site } from "sp-pnp-js/lib/sharepoint/rest/Site";
let s = new Site("https://{tenant}.sharepoint.com/sites/dev");
s.rootWeb.get().then(r => console.log(JSON.stringify(r)));

**Comment by mauricionr** [comment]
@patrick-rodgers thanks, i will try this!
