### ISSUE TITLE
Sharepoint 2013 REST API limitations with site columns

### ISSUE THREAD

**Issue by mauricionr** [OfficeDev/PnP-JS-Core#178]
#### Category
[ ] Enhancement

[ ] Bug

[X ] Question

#### Expected / Desired Behavior / Question
Suport all kind of field type

#### Observed Behavior
I'm using PnP-JS-Core and i need get some fields, but according to this link, i can't.
[Sharepoint 2013 REST API limitations with site columns](http://rayudu86.blogspot.com.br/2015/05/sharepoint-2013-rest-api-limitations.html)

They don't come with the response stuff, in others project's i get then with CSOM, at this time i really will need use CSOM?

I could not find any docs about this _api limitation on MSDN

Thanks!

**Comment by patrick-rodgers** [comment]
We are targeting REST as much as possible so if there is a gap in the API you can submit a [user voice](https://sharepoint.uservoice.com/) request to let the team know. I haven't looked at this but perhaps there is something we can add to help ease getting these fields in REST - but it looks from that article you linked that we would need to make requests for those fields separately. I am not sure that is the best solution as we wouldn't know what type of fields you really wanted and would be very hard to make generic. Likely the best option is to make the request using the html value as shown for those fields. You could chain the operations together with .then() and aggregate the result on a single object. This is a good candidate for a sample rather than an update to the core library - but open to options.

**Comment by mauricionr** [comment]
@patrick-rodgers it works, i found this columns on FieldValuesAsHtml, Thanks!

**Comment by MarkStokes-outlook** [comment]
Does anyone have a code sample for this?

**Comment by phillipharding** [comment]
This is a huge ommission from the MS team, after all the REST API can return a Publishing HTML field without a problem, the workaround only works when you're after a single item, if you're looking for a list of items (which includes a Publishing Image column) you're out of luck.

[Retrieve Publishing fields using SharePoint 2013 REST](http://stackoverflow.com/questions/25852997/retrieve-publishing-image-field-with-sharepoint-2013-rest-api-csom)

**Comment by MarkStokes-outlook** [comment]
It really is.  I have just sussed it though.  Shame as this is a major performance hit.

`$pnp.sp.web.lists.getByTitle('Pages').items
                .select("Title", "ID", "Country","ArticleStartDate")
                .top(4)
                .get().then(function(items) {
                    for (var i = 0; i < items.length; i++) {
                        // variables required to access data in the next promise
                        var thisItemID = items[i].ID;
                        var thisItemCountry = items[i].Country;
                        var thisItemTitle = items[i].Title;
                        var thisItemArticleStartDate = items[i].ArticleStartDate;

                        $pnp.sp.web.lists.getByTitle('Pages').items.getById(items[i].ID)
                            .select("ID", "PublishingRollupImage")
                            .fieldValuesAsHTML.get().then(function(itemHTMLFields){
                                    
                                $("#cs-search-results").append(RedPlane.CaseStudies.displayTemplate.replace("{0}", thisItemID).replace("{1}", itemHTMLFields.PublishingRollupImage).replace("{2}", thisItemCountry).replace("{3}", thisItemTitle).replace("{4}", thisItemArticleStartDate));
                                });
                        }

            })`

**Comment by mauricionr** [comment]
I could found the `PublishingRollupImage` expanding `FieldValuesAsText` and accessing the propertie `FieldValuesAsText.MetaInfo`

**Comment by phillipharding** [comment]
I've found a way to do this without multiple REST calls, though its a bit schloppy.

First the **REST** call:
`{site url}/_api/web/lists/getbytitle('Pages')/items?$select=Id,Title,FieldValuesAsText/MetaInfo&$expand=FieldValuesAsText`

Then to get at the **PublishingRollupImage** in the response items you have to parse out the **MetaInfo** field value which contains all field values separated by the **`\r\n`** character, each column value is then formatted as `{FieldName}:{FieldType}|{FieldValue}`;

`foreach (item in response.items) {
     var pubImage = (item.MetaInfo || "")
                                   .split('\r\n')
                                   .filter(function(e) { 
                                       return e.match(/^PublishingRollupImage:SW/gi); 
                                   } ).map(function(e) { 
                                       return e.split('|')[1]; 
                                   });
}`

**Comment by MarkStokes-outlook** [comment]
Awesome stuff.  I will try this out myself.

**Comment by MarkStokes-outlook** [comment]
I have tried this, but I am not getting the MetaInfo object returned:

```
$pnp.sp.web.lists.getByTitle('Pages').items
.select("Title", "ID", "Country", "ArticleStartDate","FileRef", "Brands", "CaseStudyCategory", "FieldValuesAsText/MetaInfo")
.filter(RedPlane.CaseStudies.Search.getFilter())
.expand("FieldValuesAsText")
.get().then(function(items) { ... });
```

**Comment by phillipharding** [comment]
Does the REST url PnP creates look correct?

**Comment by mauricionr** [comment]
```javascript
$pnp.sp.web.lists.getByTitle('Pages').items
.select("Title", "ID", "Country", "ArticleStartDate","FileRef", "Brands", "CaseStudyCategory", "FieldValuesAsText")
.filter(RedPlane.CaseStudies.Search.getFilter())
.expand("FieldValuesAsText")
.get().then(function(items) { ... });
```

@MarkStokes-outlook try this one!

**Comment by emp** [comment]
MetaInfo seems to be pretty heavy the more content you have in each item. If you're building something that's a very average news widget where you just display title, image and some small bit of extra info its probably a bad use case to download its entire PublishingPageContent for example.

I will insist about the omission here mentioned by @phillipharding, if we want to eagerly load these properties just make the API do so already, its been years [wasn't even possible via REST for a long time].

**Comment by P3nf0ld** [comment]
This thread helped me a lot, and eventually enabled me to get the Publishing RollupImage with the FileRef and Title fields I was able to create a news slider..(not exciting I know) anyway heres the complete code for those looking to use pnp.js directly:

$pnp.sp.web.lists.getByTitle("Pages").items.select("Title", "FileRef","fieldValuesAsText/MetaInfo")
			.filter("Title ne 'Page not found'").top(4).orderBy("Modified")
			.expand("fieldValuesAsText").get().then(function (result) {
					for (var i = 0; i < result.length; i++) {           
						var pubImage = (result[i].FieldValuesAsText.MetaInfo || "")
							.split('\r\n')
							.filter(function(e){return e.match(/^PublishingRollupImage:SW/gi);})
							.map(function(e) {return e.split ('|')[1];});
							
						console.log(result[i].Title);
						console.log(result[i].FileRef);
						console.log(pubImage[0]);
					}	
			 
		});
