### ISSUE TITLE
Adher to TS doc naming conventions for interfaces? (styleguide?)

### ISSUE THREAD

**Issue by pbjorklund** [OfficeDev/PnP-JS-Core#18]
In http://www.typescriptlang.org/docs/handbook/writing-definition-files.html says:

_In general, you shouldn’t prefix interfaces with I (e.g. IColor). Because the concept of an interface in TypeScript is much more broad than in C# or Java, the IFoo naming convention is not broadly useful._

What stances does this repo take? Is there a styleguide being worked on to declare things like naming conventions, recommended patterns etc etc?

**Comment by patrick-rodgers** [comment]
We have discussed a need for a style guide, but as with so many things it is on the todo list. Hoping to make some progress this week now that I am back on some of the documentation related activities. Welcome any help of course :)

As for interface names - that makes sense, we should try and adhere to the published handbook, so likely have some changes to make in the code related to this.

**Comment by patrick-rodgers** [comment]
Going to close this issue and create a starting page for a style guide in the wiki. Initially we will just use the link you provided, but can grow/update as our needs dictate.

**Comment by pbjorklund** [comment]
I added interface naming to the wiki https://github.com/OfficeDev/PnP-JS-Core/wiki/Style-Guide @patrick-rodgers. Let me know if you don't agree.
