### ISSUE TITLE
Error: Cannot find module './fetchclient' on ubuntu

### ISSUE THREAD

**Issue by mauricionr** [OfficeDev/PnP-JS-Core#183]
#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Expected / Desired Behavior / Question
load pnp library

#### Observed Behavior
Error: Cannot find module './fetchclient'

#### Steps to Reproduce
run `npm install sp-pnp-js`
require this library in index.js file `const pnp = require('sp-pnp-js');`
run `node index.js`

![image](https://cloud.githubusercontent.com/assets/2263551/17911747/c1e62a1c-6965-11e6-9e8e-98462bacc12c.png)

Thanks!

**Comment by patrick-rodgers** [comment]
Closing this based on merge of #184. Thanks!
