### ISSUE TITLE
Missing node-fetch in rendered SPFx client-side web-part

### ISSUE THREAD

**Issue by SPDoctor** [OfficeDev/PnP-JS-Core#185]
#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Expected / Desired Behavior / Question
Dependencies such as node-fetch should be installed when the npm package is installed.

#### Observed Behavior
On building an SPFx client-side web-part using sp-pnp-js library I get a runtime error in the rendered web part that the module node-fetch is missing. 

![image](https://cloud.githubusercontent.com/assets/10207194/17985454/c59c7554-6b0d-11e6-8a79-210daacd7f1b.png)

#### Steps to Reproduce
Create a client-side web-part using **yo @microsoft/sharepoint**. Add pnp-JS-Core library using **npm install --save sp-pnp-js**. Reference sp-pnp-js in the web part. Test the web part in the workbench using **gulp serve**.

#### Workaround
If I run **npm install --save node-fetch** the problem goes away. Should node-fetch be moved from devDependencies to dependencies?

**Comment by johnnliu** [comment]
we had a discussion about this in gitter https://gitter.im/OfficeDev/PnP-JS-Core?at=579df1917fd9f73e16ee89aa regarding the node-fetch dependency introduced as part of 1.0.3

technically, whether node is required depends on the target build from webpack.  If webpack target=web, then node-fetch should NOT be included, as the js is designated to go to the client.  However, if webpack target=node, then node-fetch is needed.

As a consumer - we can modify our webpack.config to ignore node-fetch dependency for target=web.  But for SPFx, the webpack config is hidden away from the user.

I asked on stackoverflow about how to do this from the library's point of view.  So pnp-js-core can detect and respond to webpack - http://stackoverflow.com/questions/38908382/in-our-library-how-to-tell-webpack-to-skip-dependencies  Sean Larkin from Webpack got back to us and gave us a link to an example.

**Comment by johnnliu** [comment]
If you have access to your web.config, I've found this works the best.

```
externals: {
 'node-fetch': '{}'
 },

```

I tell webpack ah don't worry about that node-fetch thing, it's already available as {}
So webpack happily skips it.

**Comment by SPDoctor** [comment]
Thanks, @johnnliu. That would definitely be a better workaround, as including node-fetch adds triples the size of the distribution file. But I couldn't find webpack.config - it must be buried deep in the SharePoint Framework build system and I haven't got to grips with this yet.

In any case, if this is the main use-case or the library we need to either fix it in the library or fix it in the SharePoint Framework. It feels like the root problem is here, not in SPFx. Perhaps an option would be to build a distribution that omits the reference to node-fetch, or change the default to not require it.

**Comment by johnnliu** [comment]
I found it.  https://github.com/defunctzombie/package-browser-field-spec 

When 'browser' is specified in a package.json - we can specify a different starting point for bundlers (browserify, webpack) for target=browser.  Otherwise it will default to main...

And then I go and check package.json and it's already there!  But it's wrong.  
![image](https://cloud.githubusercontent.com/assets/1279372/18000372/00bbadae-6bc1-11e6-9190-8b6e7e4b5b1b.png)

**Comment by johnnliu** [comment]
Change to 

`    "./lib/net/nodefetchclient.js": "./lib/net/nodefetchclientbrowser.js"
`

Seems to fix it for me.

**Comment by SPDoctor** [comment]
That fix seems to work - awesome! I fixed it locally by going to node-modules/sp-pnp-js/package.json and finding the browser section and changing it per your PR.
