### ISSUE TITLE
syntax error: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by AvniBhatt** [OfficeDev/PnP-JS-Core#186]
Category : Question

I am using SharePoint 2013 On-Premise. I have written following code to get web title and description:
`$pnp.sp.site.rootWeb.get().then(function(web) {  

  document.getElementById("sample").innerText = "Title: " + web.Title + "\r\n" + "Description: " + web.Description;  
  
}).catch(function(err) {  
   alert(err);  
});  
`

But I am getting following error:

`syntax error: Unexpected token < in JSON at position 0`

Am I missing something here?

Thanks!

**Comment by mauricionr** [comment]
@AvniBhatt have you followed this step [Install and use](https://github.com/OfficeDev/PnP-JS-Core/wiki/Install-and-Use)?

**Comment by patrick-rodgers** [comment]
It sounds like you are targeting an on-prem environment with the minimal metadata options disabled. This was fixed, please see this #127 for details. You can also [see my blog post](https://blogs.msdn.microsoft.com/patrickrodgers/2016/06/13/pnp-jscore-1-0-1/) from when this was added to the library. Please give this a try and let us know if it resolves your issue.

**Comment by AvniBhatt** [comment]
Yes it worked. Thank You
