### ISSUE TITLE
How can I query a list from other site collection?

### ISSUE THREAD

**Issue by lambertqin** [OfficeDev/PnP-JS-Core#188]
#### Category
[ ] Question

How can I query a list from other site collection?
for example, I am in site collection A (sites/a), if I want to get a list item from site collection B(sites/b). how can i do that?
I googled a lot, but it seems all samples are within same site. like pnp.sp.web.***

Thanks!

**Comment by mauricionr** [comment]
@lambertqin i guess is not possible yet, checkout these issues #182 #173

**Comment by patrick-rodgers** [comment]
You can do this by creating a new Site or Web object with the full url as here:

import { Site } from "sp-pnp-js/lib/sharepoint/rest/Site";
let s = new Site("https://{tenant}.sharepoint.com/sites/dev");
s.rootWeb.get().then(r => console.log(JSON.stringify(r)));
