### ISSUE TITLE
sp-pnp-js@1.0.4 fails when trying to use

### ISSUE THREAD

**Issue by NPrice99** [OfficeDev/PnP-JS-Core#191]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Observed Behavior
sp-pnp-js should just compile successfully.  It does not.  I get error 👎 

 sp-pnp-js@1.0.4 postinstall: `typings install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sp-pnp-js@1.0.4 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sp-pnp-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sp-pnp-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sp-pnp-js
npm ERR! There is likely additional logging output above.

#### Steps to Reproduce
Use SPDoctor's client webpart demo'ed at last Thursday's meeting.  Get above error when compiling. using Node v4.5.0 and npm V3.10.7,
I have recently upgraded both as per Vesa's / Pat Miller's instructions as a new release of the SPFx framework has been made available. https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-Drop-2

Nigel

**Comment by NPrice99** [comment]
I fixed this error with npm install -g typings --save However, I now get this message - 
Error - typescript - src\webparts\siteInfo\components\SiteInfo.tsx(3,22): error TS2307: Cannot find module 'sp-pnp-js'.

Yet this says it is installed - 

C:\XXXX\YYYY\ZZZZ\Documents\SPFx\Projects>npm install -g sp-pnp-js

> sp-pnp-js@1.0.4 postinstall C:\XXXX\YYYY\AppData\Roaming\npm\node_modules\sp-pnp-js
> typings install


+-- chai (global)
+-- chai-as-promised (global)
+-- es6-promise (global)
+-- microsoft.ajax (global)
+-- mocha (global)
+-- promises-a-plus (global)
+-- sharepoint (global)
`-- whatwg-fetch (global)

C:\XXXX\YYYY\AppData\Roaming\npm
`-- sp-pnp-js@1.0.4

Regards

Nigel

**Comment by NPrice99** [comment]
Hi


I finally got this to work by doing the following :-

I tried npm install -g sp-pnp-js --save

That did not work.

But npm install --save sp-pnp-js did work !!


So why could I not install sp-pnp-js globally ??


Regards


Nigel

**Comment by patrick-rodgers** [comment]
This is resolved as discussed in Yammer, please do let us know if you have any other issues. Thanks!

**Comment by kchiragowni** [comment]
Hi @patrick-rodgers , I wanted to install and use SP-PNP-JS in our JavaScript app and when I'm trying to install I'm getting the same error (postinstall: 'typings install') failed. I don't want to use typescript/typings in my JS projects. Can I use this library in our JS project (ES6, React and Redux)?

**Comment by russgove** [comment]
Hi Kiran,
You should be able to just download pnp.js from the dist floder (
https://github.com/OfficeDev/PnP-JS-Core/blob/master/dist/pnp.js) and
include it in your project. No build required.
Russell
