### ISSUE TITLE
SharePoint 2013 - rest api query fails with "Invalid character" error

### ISSUE THREAD

**Issue by ivanvagunin** [OfficeDev/PnP-JS-Core#192]
#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Expected / Desired Behavior / Question
Expected not to fail

#### Observed Behavior
When execute query against SharePoint 2013 farm, it fails with "Invalid character" error.

#### Steps to Reproduce
let item = pnp.sp.web.lists.getById(listId).items.getById(itemId);
item.get().then((item) => {}).catch(err => {
    pnp.log.write(err, pnp.log.LogLevel.Error);
});

#### Proposed fix
It happens because SharePoint 2013 return atom xml formatted response, despite Accept header set to application/json. It returns JSON when Accept header set to "application/json;odata=verbose" and Content-Type to "application/json". For example:

1) This returns JSON
GET http://portal/_api/web/lists('%7BA9756F71-F998-45C2-8D6A-166EB35D87C9%7D')/items(2)
Content-Type: application/json;odata=verbose
Accept: application/json;odata=verbose

2) This returns ATOM XML
GET http://portal/_api/web/lists('%7BA9756F71-F998-45C2-8D6A-166EB35D87C9%7D')/items(2)
Content-Type: application/json;odata=verbose
Accept: application/json

So proposed fix is to set Accept header like this:
headers.append("Accept", "application/json;odata=verbose");
It works with SharePoint 2013, but not sure if it works with other versions

**Comment by patrick-rodgers** [comment]
Please see #186, this has been addressed several times previously. Also covered in the release notes for the 1.0.1

**Comment by ivanvagunin** [comment]
indeed, thanks!
