### ISSUE TITLE
Adding a file content into a Folder using the Blob interface

### ISSUE THREAD

**Issue by arheom** [OfficeDev/PnP-JS-Core#195]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Question
I am trying to use the Folder.files.add function to upload a document into a folder, but I am struggling with the parameters.
The method is inside the files.ts (Folder):
`public add(url: string, content: Blob, shouldOverWrite = true)`
and the content parameter is of type Blob:
`interface Blob {
    size: number;
    type: string;
    msClose(): void;
    msDetachStream(): any;
    slice(start?: number, end?: number, contentType?: string): Blob;
}`
How I can fill out this parameter to have it working? I have the fileName and the content and as I know from the REST api I need to put the content into the body of the post request, but not sure how I can translate my object to this Blob type parameter. Any idea?

Thanks!

**Comment by patrick-rodgers** [comment]
If you get the file from the input, this example uses jquery you should be able to pass that as the blob.

`var file = $(this).find("input")[0].files[0];`

**Comment by arheom** [comment]
Not sure if I got your example. I am using Typescript, so I need to pass a Blob object, defined in Typescript. In javascript I can just pass the content as Blob object and should work, but in Typescript I get an error and not sure how I can solve it.

**Comment by patrick-rodgers** [comment]
Since you haven't shared the error you are getting I am having to guess it is a typing error. The below is correctly typed when I test it. Can you do something like that?

```
import pnp from "sp-pnp-js";

// assumes you get the file input from a form
let fileInput: HTMLInputElement;

let file = fileInput.files[0];

pnp.sp.web.getFolderByServerRelativeUrl("/path/to/my/folder").files.add("myfile.docx", file, true);
```

**Comment by mauricionr** [comment]
@patrick-rodgers the file don't need use `FileReader ` API to `readAsArrayBuffer` and then pass to this method `add()`?

**Comment by arheom** [comment]
@patrick-rodgers: Yes, it is only a typing issue. I actually have the following scenario: I read one file from one url (using $.ajax) and transform the content into an ArrayBuffer. I pass this one to the pnp, like:
pnp.sp.site.rootWeb.getFolderByServerRelativeUrl(targetFolderUrl).files.add(fileName, buffer as Blob)
And it works. But I needed to overwrite the typing for Blob to be able to have it working like that.

**Comment by patrick-rodgers** [comment]
@mauricionr - in my testing when I wrote it no, just appending the blob works. If that is not the case we can re-visit.

@arheom - going to close this issue as resolved, please do let us know if that is not the case.
