### ISSUE TITLE
Provisioning Sequencer not working

### ISSUE THREAD

**Issue by arheom** [OfficeDev/PnP-JS-Core#196]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Description
I created one provisioning file and tested it against the provisioning framework from pnp. The sequencer.execute method fails to work, because there are a lot of anonymous functions which will hide the this object and eventually inside the this.scope, this.parameter will return undefined.
In order to work, we need to transform it with => "fat arrow", so the "this" object will be maintained inside the anonymous functions:

Example:
`.then(function (result) { // Resolve for each function call
                if (progressFunction) {
                    progressFunction.call(this, functionNr, this.functions);
                }
            });`
should be transformed to
`.then((result) => { // Resolve for each function call
                if (progressFunction) {
                    progressFunction.call(this, functionNr, this.functions);
                }
            });`

Thanks!

**Comment by patrick-rodgers** [comment]
Fixed in #200 and merged to dev
