### ISSUE TITLE
Provisioning ObjectHandlers/objectlists.ts issue on GetFieldXml

### ISSUE THREAD

**Issue by arheom** [OfficeDev/PnP-JS-Core#197]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Description
The FieldXml element is not created correctly inside this method, because of a wrong placement of a line inside the GetFieldXml method (objectlists.ts file):
`properties.push(`${prop}="${value}"`);`
should be moved outside of the if:
`if (prop === "List") {`
because now will only add the property if it is named List and should work with all properties. Once the line is added after the if from above, the Fields are getting provisioned.

Thanks!

**Comment by patrick-rodgers** [comment]
Fixed in #200 and merged to dev
