### ISSUE TITLE
Unable to sort items descending

### ISSUE THREAD

**Issue by waldekmastykarz** [OfficeDev/PnP-JS-Core#198]
#### Category
[ ] Enhancement
[x] Bug
[ ] Question

#### Expected / Desired Behavior / Question
When calling `pnp.sp.web.list.get().items.orderBy('Id', false)` the REST query should contain `$orderby=Id desc`.
Currently the second parameter in the `orderBy` function determines whether sorting should be done ascending. Given that that's the default setting, consider changing the second parameter to descending so that when set, it explicitly adds `desc` to the `$orderby` clause in the REST query.

#### Observed Behavior
The generated query contains `$orderby=Id`.

#### Steps to Reproduce
Try getting items sorted descending using `pnp.sp.web.list.get().items.orderBy('Id', false)`

**Comment by koltyakov** [comment]
Hi Waldek,

This one seems to be an easy one to fix.
I've created a pull request https://github.com/OfficeDev/PnP-JS-Core/pull/199 with the fix.

**Comment by patrick-rodgers** [comment]
Closing based on merge of #199.
