### ISSUE TITLE
Core.JavaScript: Util.ts - other external dependencies

### ISSUE THREAD

**Issue by patrick-rodgers** [OfficeDev/PnP-JS-Core#2]
When we're building the Util.ts (general JavaScript helpers/utilities), we will probably start to reflect many of the functions that already exists in underscore.js (http://underscorejs.org/).

Is this a problem? Could it be an idea to depend on it? The production dist is very lightweight (approx 5kb).

**Comment by nerdondon** [comment]
hi patrick,
regarding underscore, i think that the tendency of the community has moved towards lodash over underscore and i believe that there are performance reasons for this as well.

another thing to consider here is that lodash makes individual modules available on npm. so we can cherry pick only the necessary modules if size really is an issue. Personally, I don't see 5kb as too big

**Comment by alex-randall** [comment]
Less external library dependencies we have, the easier it will be to use and not cause potential runtime conflicts (thinking site owner scenarios who are coding JavaScript in Script Editor/Content Editor Web Parts and many others).

**Comment by patrick-rodgers** [comment]
Going to close this one - I think great points and we will aim to limit the number dependencies. This is why we have created our own utils library to not take a dependency for a few lines of code. Thanks for the input guys!
