### ISSUE TITLE
Export Web

### ISSUE THREAD

**Issue by Djemel** [OfficeDev/PnP-JS-Core#201]
[ ] Enhancement

[ ] Bug

[X ] Question

I am loading the sp-pnp-js library from our own CDN and using "pnp.sp...." using:
import * as pnp from "sp-pnp-js";

But in my script I also need to talk to "other" web to get and write data, so I am also using:
let anotherweb = new Web('https://mysharepoint.local/sites/team/anotherweb');
and in order for that to work I need to add:
import { Web } from "sp-pnp-js/lib/sharepoint/rest/webs";

Unfortunately, that does not work fine with bundling made by webpack as Web is not exported in the pnp JS library.

I know "exports" was already discussed but in that specific case, it would be use full to have a few object like Web, Site ... constructors exported.
How could this be solved ?

**Comment by patrick-rodgers** [comment]
Great question, let me think about it as this has come up in a few cases from various angles. Open to suggestions from folks as well.

**Comment by patrick-rodgers** [comment]
Small update - still working on this, but had a laptop die (and I was a bad developer and wasn't daily shelving my work) so I've lost what I did. Will continue working on this and plan to include in 1.0.5 hopefully late this week or early next week.

**Comment by patrick-rodgers** [comment]
Closing based on #213. Now exporting many of the internals - will detail in release blog post but if you pull dev branch you can now do the following and it works with webpack bundling (at least the way I had webpack configured for testing :) )

```
import { Web } from "sp-pnp-js"
let w = new Web("https://{url}");
w.get().then(...)
```

**Comment by Djemel** [comment]
Thank you very much for the implementation - it works like a charm.
