### ISSUE TITLE
How to add items using batch

### ISSUE THREAD

**Issue by mauricionr** [OfficeDev/PnP-JS-Core#202]
#### Category
[ ] Enhancement

[ ] Bug

[X ] Question

#### Expected / Desired Behavior / Question
add multiple items

#### Observed Behavior
i'm getting GET request instead of POST

#### Steps to Reproduce
```javascript

var batch = $pnp.sp.createBatch();
var promises = [];

promises.push($pnp.sp.web.lists.getByTitle('Batch').items.inBatch(batch).add({Title:Date.now().toString()}))
promises.push($pnp.sp.web.lists.getByTitle('Batch').items.inBatch(batch).add({Title:Date.now().toString()}))

Promise.all(promises).then(function(){
	console.log(arguments)
})

```
Thanks!

**Comment by mauricionr** [comment]
add in Items already use batch `addBatchDependency` ?

**Comment by koltyakov** [comment]
Did you try to use:

```javascript
batch.execute();
```

This works for me:

```javascript
var batch = new $pnp.sp.createBatch();
var promises = [];

for (var i = 0, len = 25; i < len; i += 1) {
   promises.push($pnp.sp.web.lists.getByTitle('Custom03').items.inBatch(batch).add({ "Title": "Title " + i }));
}

Promise.all(promises).then(function() {
    console.log("Batch items creation is completed");
});

batch.execute();
```

**Comment by patrick-rodgers** [comment]
Yes, I believe @koltyakov is correct and you are missing the batch.execute call, which now as of 1.0.4 also returns a promise so you no longer need to build the promises array (though you can, nothing stops what you are doing from working).

**Comment by koltyakov** [comment]
Hi Patrick,

I have a following behavior:

```javascript
batch.execute().then(function() {
   // promise all works for GET request in a batch only, if there is at least one POST it doesn't fire this event
});
```

So in case of POST requests `Promise.all` is an option.

**Comment by patrick-rodgers** [comment]
@koltyakov - That sounds like a bug in how I implemented that - so need to please log that as a separate issue so we can take a look. Thanks!

**Comment by mauricionr** [comment]
@koltyakov  @patrick-rodgers in this case

```javascript
batch.execute().then(function() {
   // promise all works for GET request in a batch only, if there is at least one POST it doesn't fire this event
});
```
The then callback means that all request were executed, or all request have been passed to batch service and the batch will work in these requests.

in my scenario i need to pass a lot of data to be created in a list, but the problem is when the user refresh the page, not all request are completed.

got it?

**Comment by koltyakov** [comment]
This is related to the JS app's logic more than to PnP-JS-Core and batching.
Batching has a "reasonable" limitation to the amount of the requests in a package.
I would recommend to tweak the size of a batch for your case (25 requests per batch, for instance), block UI detecting saving process (progress bar is perfect here) and call next batch chunk after the previous one completion callback. 
By sending large batch data can definitely be lost.

**Comment by patrick-rodgers** [comment]
The design is that the promise returned from the batch's execute should resolve once all of the "child" promises have resolved. There is nothing we can to if the user refreshes the page while things are running as there is no way to recover/track state in that case. Long running operations are best moved to a remove service you can call from your application - that way if the user closes the page or whatever it can still complete. And as mentioned above there are limits to how much can be passed in a single batch. In this case I think the solution might be a remove service, especially if there is a lot of data/time potentially required.

**Comment by patrick-rodgers** [comment]
Going to close this one as it appears to be addressed, please reopen if that is not the case. Thanks everyone for the discussion!
