### ISSUE TITLE
How to work with a lots of items(>= 10000) and generate reports

### ISSUE THREAD

**Issue by mauricionr** [OfficeDev/PnP-JS-Core#204]
#### Category
[ ] Enhancement

[ ] Bug

[ X] Question

### Question

I have a scenario that i need work with big data in sharepoint but the rest api looks like not full feature
wich is the best practice for this?(use JavaScript CSOM?)

Thanks!

**Comment by koltyakov** [comment]
Hi Mauricio,

I usually deal with this by chunking result data to return less than 5000 logically (or whatever is a throttling limit in the environment). And merging result on a client, if you really need a "view" in your app/report with more than 5000 items. Where is possible, such scenarios should be avoided, as heavy and is better to use the search API and paging.

Example of a chunk data request:

```javascript
var getRecursive = function(callback, lii, items) {
   var lii = lii || -1;
   var items = items || [];
   var q = $pnp.sp.web.lists.getByTitle('Custom03').items.top(5000);
   if (lii !== -1) {
      q = q.skip(lii);
   }
   q.get().then(function(res) {
      if (res.length === 0) {
         if (callback && typeof callback === "function") {
            callback(items);
         }
      } else {
         items = items.concat(res);
         getRecursive(callback, res[res.length - 1].Id, items);
      }
   });
};
getRecursive(function(results) {
   console.log(results.length); // All the items in a list
});
```

**Comment by patrick-rodgers** [comment]
There is currently no way (nor should there be from the client) a way to circumvent around the API limits. So you would need an approach similar to what @koltyakov posted. You can also see [this sample](https://github.com/OfficeDev/PnP/blob/master/Samples/SharePoint.pnp-js-core/SharePoint.pnp-js-core/Samples/ReadListItemsPaged.html) using the library to page through the results, which could be used to aggregate more data across many items.

**Comment by patrick-rodgers** [comment]
Going to close this as well, it appears to be answered with a good code sample. Please re-open if things aren't clear.
