### ISSUE TITLE
Get a specific list from a specific sub web of a site collection?

### ISSUE THREAD

**Issue by arheom** [OfficeDev/PnP-JS-Core#205]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Question
I am trying without success to get a list with a specific title, from a specific subsite and cannot find a way. In REST Api I was directly change the URL of the _api, but not sure how to do it here:
I would like to get the web with Title 'de' and from inside to get a list with the Title 'fish' for example. Tried multiple ways, but none worked for me. I think the main question is to get a specific subweb of a root web and process it further from there, something like:
pnp.sp.site.rootWeb.webs("de").lists.getByTitle....

Thanks a lot!
Bogdan

**Comment by koltyakov** [comment]
Hi, 

+1

Also interested in a correct way for achieving this.
I know one hack - changing `_spPageContextInfo.webAbsoluteUrl` in runtime.

Like: 

```javascript
var requestWithAnotherWebContext = function(webRelativeUrl, callback) {
   _webAbsoluteUrl = _spPageContextInfo.webAbsoluteUrl;
   _spPageContextInfo.webAbsoluteUrl = window.location.origin + webRelativeUrl;
   if (callback && typeof callback === "function") {
      callback();
   }
   _spPageContextInfo.webAbsoluteUrl = _webAbsoluteUrl;
};

$pnp.sp.web.get().then(function(web) {
   console.log({
      Query: "Current",
      Title: web.Title,
      ServerRelativeUrl: web.ServerRelativeUrl
   });
});
requestWithAnotherWebContext("/sites/dev01/test01", function() {
   $pnp.sp.web.get().then(function(web) {
      console.log({
         Query: "Custom",
         Title: web.Title,
         ServerRelativeUrl: web.ServerRelativeUrl
      });
   });
});

// Object {Query: "Current", Title: "Dev 01", ServerRelativeUrl: "/sites/dev01"}
// Object {Query: "Custom", Title: "test01", ServerRelativeUrl: "/sites/dev01/test01"}
```

Yet, this is just a workaround.

**Comment by patrick-rodgers** [comment]
This should work:
```
import pnp from "sp-pnp-js";
import { Web }  from "sp-pnp-js/lib/sharepoint/rest/webs";

let web = new Web("{absolute URL to web}");
web.lists.getByTitle("de").get().then(l => {
    console.log(l.Title);
});
```

**Comment by patrick-rodgers** [comment]
Going to close this as answered, please let us know if things remain unclear. Thanks!

**Comment by dhavalshah01** [comment]
Hi @patrick-rodgers 

How can I implement the same in Javascript ?

**Comment by koltyakov** [comment]
Hi there,

The vanilla JS way (in browser's page) is almost identical:

```javascript
var web = new $pnp.Web('{absolute URL to web}');
web.lists.getByTitle('de').get().then(function(l) {
    console.log(l.Title);
});
```

**Comment by patrick-rodgers** [comment]
Hi @dhavalshah01 - @koltyakov is correct, you can also use [this wiki page](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Webs#get-a-web-directly) for reference as well.

**Comment by Ofer-Gal** [comment]
I am using this. I get the results but also an error:
`pnp.min.js:1 GET https://c3dev.novuslaw.com/clients/AvisBudget-Ahmed/_api/web/lists/getByTitle('Knowledge%20Item')/items?$select=Title,NLC3KnowledgeItemCategoryId 404 (Not Found)
t.fetch @ pnp.min.js:1
i @ pnp.min.js:1
(anonymous) @ pnp.min.js:1
e.fetchRaw @ pnp.min.js:1
e.fetch @ pnp.min.js:1
(anonymous) @ pnp.min.js:1
e.send @ pnp.min.js:1
n.value @ pnp.min.js:1
i @ pnp.min.js:1
(anonymous) @ pnp.min.js:1
Promise.then (async)
n.value @ pnp.min.js:1
i @ pnp.min.js:1
(anonymous) @ pnp.min.js:1
Promise.then (async)
n.value @ pnp.min.js:1
i @ pnp.min.js:1
a @ pnp.min.js:1
(anonymous) @ pnp.min.js:1
Promise.then (async)
e.get @ pnp.min.js:1
reloadKIs @ KIMaker.js:29
(anonymous) @ KIMaker.js:22
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
K @ jquery.min.js:2
pnp.min.js:1 Uncaught (in promise) Error: Error making HttpClient request in queryable: [404] Not Found
    at new t (pnp.min.js:1)
    at pnp.min.js:1`

**Comment by koltyakov** [comment]
Hey @Ofer-Gal,
 
The resource which is requested by the script doesn't exist, that's why `404, Not found`.

Could you please check what is the response message (network tab in ChromeDevTools)?
It can be something like this:

![image](https://user-images.githubusercontent.com/7816483/38887539-c803195e-4281-11e8-84bd-b1d446c6a766.png)

In many cases, REST response is quite verbose and meaningful. 

My bet is that the display name for the list is different. It's always better getting lists by `web/getList([list relative URL])`.
