### ISSUE TITLE
Typing's dependency needed to compile

### ISSUE THREAD

**Issue by rgarita** [OfficeDev/PnP-JS-Core#206]
#### Category
[ X] Enhancement

[ ] Bug

[ ] Question

#### Expected / Desired Behavior / Question
When you import the library using npm, the desired behavior is be able to compile all without problems. Or at least have the instructions on how get the environment ready  . I was having a TS compilation issue over some .d.ts files, mostly about the Response class.

<img width="335" alt="2016-09-28_9-46-15" src="https://cloud.githubusercontent.com/assets/161268/18921028/800426aa-8560-11e6-83ec-3f5062ae1e90.png">

Checking the github solution and looking into the typings.json on this project i figure out that I need to add some extra typing's into my project to be able to compile. the required typing is "whatwg-fetch"

#### Steps to Reproduce
I'm using a Yeoman generation : fountain-react generator
Just use npm and import any module on your   solution

**Comment by okaufmann** [comment]
Same described in https://github.com/OfficeDev/PnP-JS-Core/issues/212

**Comment by patrick-rodgers** [comment]
Closing this based on #215. Documentation updates pending in wiki
