### ISSUE TITLE
Typescript error when build the project

### ISSUE THREAD

**Issue by ravenboilinux** [OfficeDev/PnP-JS-Core#212]
#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Expected / Desired Behavior / Question
Gulp should build the typescript completely

#### Observed Behavior
Everytime I build the my project that use the pnp framework i get this error
[14:59:47] ==================[ Finished ]==================
Error - typescript - node_modules\sp-pnp-js\lib\net\httpclient.d.ts(3,15): error
 TS2304: Cannot find name 'HeaderInit'.
Error - typescript - node_modules\sp-pnp-js\lib\net\httpclient.d.ts(6,12): error
 TS2304: Cannot find name 'BodyInit'.
Error - typescript - node_modules\sp-pnp-js\lib\net\httpclient.d.ts(7,21): error
 TS2304: Cannot find name 'RequestMode'.
Error - typescript - node_modules\sp-pnp-js\lib\net\httpclient.d.ts(8,28): error
 TS2304: Cannot find name 'RequestCredentials'.
Error - typescript - node_modules\sp-pnp-js\lib\net\httpclient.d.ts(9,22): error
 TS2304: Cannot find name 'RequestCache'.
Error - typescript - node_modules\sp-pnp-js\lib\net\httpclient.d.ts(15,57): erro
r TS2304: Cannot find name 'Response'.
Error - typescript - node_modules\sp-pnp-js\lib\net\httpclient.d.ts(16,60): erro
r TS2304: Cannot find name 'Response'.
Error - typescript - node_modules\sp-pnp-js\lib\net\httpclient.d.ts(17,55): erro
r TS2304: Cannot find name 'Response'.
Error - typescript - node_modules\sp-pnp-js\lib\net\httpclient.d.ts(18,56): erro
r TS2304: Cannot find name 'Response'.
Error - typescript - node_modules\sp-pnp-js\lib\net\httpclient.d.ts(23,47): erro
r TS2304: Cannot find name 'Response'.
Error - typescript - node_modules\sp-pnp-js\lib\sharepoint\rest\caching.d.ts(20,
21): error TS2304: Cannot find name 'Response'.
Error - typescript - node_modules\sp-pnp-js\lib\sharepoint\rest\items.d.ts(155,2
8): error TS2304: Cannot find name 'Response'.
Error - typescript - node_modules\sp-pnp-js\lib\sharepoint\rest\odata.d.ts(4,14)
: error TS2304: Cannot find name 'Response'.
Error - typescript - node_modules\sp-pnp-js\lib\sharepoint\rest\odata.d.ts(7,14)
: error TS2304: Cannot find name 'Response'.
Error - typescript - node_modules\sp-pnp-js\lib\sharepoint\rest\odata.d.ts(12,14
): error TS2304: Cannot find name 'Response'.
Error - 'typescript' sub task errored after 3.83 s
 "TypeScript error(s) occurred."

#### Steps to Reproduce
1) npm install sp-pnp-js --save
2) run gulp

**Comment by patrick-rodgers** [comment]
Thanks for reporting this, I just started noticing this myself - which makes me think something changed in a dependency. Will take a look.

**Comment by okaufmann** [comment]
Same here, built with webpack...

**Comment by okaufmann** [comment]
When I add the following line to typings.json it builds.

```
"whatwg-fetch": "github:DefinitelyTyped/DefinitelyTyped/whatwg-fetch/whatwg-fetch.d.ts#9027703c0bd831319dcdf7f3169f7a468537f448"
```

`whatwg-fetch` was removed in a previous commit, so this could be the source of the problem:
https://github.com/OfficeDev/PnP-JS-Core/commit/41bf53815a53a85e391c5dd0fd674a8059db238b

Hope this helps.

**Comment by patrick-rodgers** [comment]
Closing this based on #215. Documentation updates pending in wiki
