### ISSUE TITLE
Profiles myProperties get parameters

### ISSUE THREAD

**Issue by showenx** [OfficeDev/PnP-JS-Core#219]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Expected / Desired Behavior / Question
Hi,
First of all, great library with big potentials, really like it, maybe need more docs to promote.

One question regarding retrieving user profile, I'm trying to retrieve part of the metadata, is there any reference for the "ODataParser" and "getOptions", or some library need to be included for this purpose.  

pnp.sp.profiles.myProperties.get(*parser*, *options*).then(function (ret) {
       //do something
})

Thanks!

**Comment by patrick-rodgers** [comment]
unsure on your need - but I think you might be looking too deep into the library. If you want only to select some of the properties you can use the select operator to do so.

```
pnp.sp.profiles.myProperties.select("AccountName", "PreferredName").get().then(d => {

    console.log(JSON.stringify(d));

});
```

Does that get you what you need?

**Comment by showenx** [comment]
yes, that's what I'm after, thanks

**Comment by patrick-rodgers** [comment]
Great, going to close the issue then. Cheers!

**Comment by Mayur-Paradkar** [comment]
What is the purpose of the query after myProperties in 

pnp.sp.profiles.myProperties.query

and how to use it.

**Comment by patrick-rodgers** [comment]
You generally would not need to access that directly, it is the dictionary where we gather up the querystring parameters.
