### ISSUE TITLE
Calling web from another folder than root...

### ISSUE THREAD

**Issue by aurelienprevotMVP** [OfficeDev/PnP-JS-Core#222]
Hi guys,

We met a problem here : when we try to use the library from a page not stored at the root of a site, we met a 404 error, because the /_api is called from the current folder, and not from the root of the current site.

Another guy met this problem here. The problem is more detailed :
https://techcommunity.microsoft.com/t5/SharePoint-Developer/PnP-JavaScript-Core-Only-for-Web-Parts/m-p/17663#M549
He didn't find any workaround...

Thanks for your help !

Best regards,

**Comment by patrick-rodgers** [comment]
I have a guess at what is happening here. The usercustomaction code is executed before the _spPageContextInfo is defined on the page. If that happens there isn't much we can do. We don't "parse" the url at all, we just look for that global var.

Starting with 1.0.5 (just released this week) you can export the Web object and set it to any url you like:

```
import { Web } from "sp-pnp-js";
let w = new Web("https://sharepoint/sites/somesite");
w.get().then(...)
```

Which would allow you to determine the url to use based on a given scenario. The reason we don't try and guess at the url is that method is bound to fail too often. So if we can't find that global var mentioned above we just make the requests to /_api/... which then in the case you linked resolves to the SitePages folder.

So two solutions to try:

1. Wait for the entire page to load before making the requests (i.e. using $(function() {}) or similar
2. Try using the Web object directly and setting the url you want explicitly.

Please let us know if either of those are helpful.

**Comment by patrick-rodgers** [comment]
This was marked as the answer on the tech community so going to close the issue here as resolved.
