### ISSUE TITLE
package.json "main" should point to ./dist/pnp.js 

### ISSUE THREAD

**Issue by johnnliu** [OfficeDev/PnP-JS-Core#228]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Expected / Desired Behavior / Question
CDNs like unpkg.com (previously npmcdn.com) and CDNJS looks for main in package.json to direct to the default file in a package.

e.g. https://unpkg.com/jquery -> see https://unpkg.com/jquery@3.1.1/package.json

for https://unpkg.com/sp-pnp-js to work, we need to change package.json to ./dist/pnp.js

for unpkg.com - you can see what's in the CDN if you suffix a trailing /

https://unpkg.com/sp-pnp-js/

**Comment by patrick-rodgers** [comment]
Issue here is I think that breaks auto-intellisense when you import into a TS project. I remember spending a few days on making that all work and in talking with someone from the TS team the way to do it is have a lib (folder name doesn't matter) with the main pointing to that and have the .d.ts files along side.

That being said I don't know how cdnjs works yet, haven't had a chance to really take a look - but will need to test it as well as ensuring things still work the way we expect.

**Comment by patrick-rodgers** [comment]
Have confirmed for cdnjs this isn't an issue. Working with those folks to get things submitted and live. Hopefully by sometime next week it will be published. Will publish a blog post as soon as it is.

For unpkg it does work if you do this: https://unpkg.com/sp-pnp-js@1.0.5/dist/pnp.js. I am not inclined to change things around to make it work with this or that CDN provider. The cdnjs folks have a nice system that doesn't require us to make changes to work with their process.
