### ISSUE TITLE
Errors using gulp serve

### ISSUE THREAD

**Issue by Mustachoman** [OfficeDev/PnP-JS-Core#229]
I am currently working on SharePoint WebParts with the new SharePoint Framework.

After following a tutorial on the Fabric UI I thought I wanted to try the PnP-JS-Core library to easily get data from SharePoint, I used normal AJAX requests before this.

However after installing the package by using `npm install --save sp-pnp-js` and then `gulp serve`-ing it I get like 210 errors saying that Typescript found an error, usually expecting a '=' or ';' and sometimes saying that there is an invalid reference.

When checking those references they seem to be OK and I think that within the package itself there are no errors. 

I also reinstalled the package multiple times and I keep getting the same errors.

Anyone else had this problem? Any idea how to tackle this?

**Comment by patrick-rodgers** [comment]
Please see #221 as well. If you update to the latest release of SPFx those errors will go away - but you'll see some other errors related to duplicate definitions. I am still working with the PG on the best way to resolve those.

For now you can peg your project as well at 1.0.4 and you should be able to continue working.

Will update #221 once I get an answer, but going to close this one as a duplicate. Thanks though for your feedback and reporting this.

**Comment by J0hnRoger** [comment]
Hello, 

Same problem here, but I don't use SPFx,  I use the project template provided by VesaJuvonen in his demonstration of modern web dev' with SPO365 :  https://github.com/SharePoint/sp-dev-samples/tree/master/Samples/react-generic-app  

![image](https://cloud.githubusercontent.com/assets/749433/21524943/0ecb61d6-cd1a-11e6-9ede-715323a84f12.png)

I update the @types but problem still here : 

![image](https://cloud.githubusercontent.com/assets/749433/21525045/d21d976c-cd1a-11e6-85f5-7098b1fecd22.png)

And I try to delete all .d.ts files in sp.pnp.js node module, errors gone, but these modules are not found after that ...  

Any idea how to tackle this?
