### ISSUE TITLE
Utility methods, when is a util method warranted?

### ISSUE THREAD

**Issue by pbjorklund** [OfficeDev/PnP-JS-Core#24]
```js
/**
 * Inserts the string s into the string target as the index specified by index
 * 
 * @param target The string into which we will insert s
 * @param index The location in target to insert s (zero based)
 * @param s The string to insert into target at position index
 */
export function stringInsert(target: string, index: number, s: string): string {
    if (index > 0) {
        return target.substring(0, index) + s + target.substring(index, target.length);
    }
    return s + target;
}
```

This reminds me of when the other PnP repo had the helper method to generate a SecureString. It was later removed due to not having the right "height".

```js
/**
 * Adds a value to a date
 * 
 * @param date The date to which we will add units, done in local time
 * @param interval The name of the interval to add, one of: ['year', 'quarter', 'month', 'week', 'day', 'hour', 'minute', 'second']
 * @param units The amount to add to date of the given interval
 * 
 * http://stackoverflow.com/questions/1197928/how-to-add-30-minutes-to-a-javascript-date-object
 */
export function dateAdd(date: Date, interval: string, units: number): Date {
    let ret = new Date(date.toLocaleString()); // don't change original date
    switch (interval.toLowerCase()) {
        case "year": ret.setFullYear(ret.getFullYear() + units); break;
        case "quarter": ret.setMonth(ret.getMonth() + 3 * units); break;
        case "month": ret.setMonth(ret.getMonth() + units); break;
        case "week": ret.setDate(ret.getDate() + 7 * units); break;
        case "day": ret.setDate(ret.getDate() + units); break;
        case "hour": ret.setTime(ret.getTime() + units * 3600000); break;
        case "minute": ret.setTime(ret.getTime() + units * 60000); break;
        case "second": ret.setTime(ret.getTime() + units * 1000); break;
        default: ret = undefined; break;
    }
    return ret;
}
```
This is hard coded against an english locale. If a good library for handling dates is needed I would suggest handling it in in the application using the PnP library with something like moment.js vs us handling dates this way in the library itself.

I would argue that methods like this perhaps doesn't need to be in the actual pnp-js-core repo since all it's doing is providing a small abstraction for simple js. (Add to that list isFunction, stringIsNullOrEmpty)

Compare with 

```js
/**
 * Loads a stylesheet into the current page
 * 
 * @param path The url to the stylesheet
 * @param avoidCache If true a value will be appended as a query string to avoid browser caching issues
 */
export function loadStylesheet(path: string, avoidCache: boolean): void {
    if (avoidCache) {
        path += "?" + encodeURIComponent((new Date()).getTime().toString());
    }
    let head = document.getElementsByTagName("head");
    if (head.length > 1) {
        let e = document.createElement("link");
        head[0].appendChild(e);
        e.setAttribute("type", "text/css");
        e.setAttribute("rel", "stylesheet");
        e.setAttribute("href", path);
    }
}
```
This helps me as a dev by providing a single way of adding stylesheets. But should it be promoted to it's own class? DocumentStyleSheetInjector ?

(I'm also curios why getRandomString is not a test helper method)

**Comment by alex-randall** [comment]
Wondering if we should not expose these util methods outside the library publically (and just use them internally) since there might be some overlap with other libraries out there.  

Or... maybe a select few functions in it should be public?

**Comment by pbjorklund** [comment]
I like having some of them exposed for doing things that are clunky. However I think they should be exposed via their own classes instead of through a 'Util' class (most obvious crime against separation of concerns)

**Comment by patrick-rodgers** [comment]
Where possible I want to avoid referencing other libraries since it would force a consumer to also include that lib to use ours. The dateAdd is there because I needed something for the cache expire stuff. I don't really want to handle dates universally. IsFunction is similar, we need that test and it takes up three lines, so I prefer not to take a dep to get three lines of code. Some of the other util methods are there because they are things I have used regularly in the past and were part of the js core from which this was derived. getRansomString forex I often use when creating dynamic DOM elements that need an ID. Always want to keep the conversation going on what makes sense vs. what doesn't, but I am OK with what we have currently.

We do currently expose them through pnp.util on the root object which simulates a class to the consumer.

**Comment by patrick-rodgers** [comment]
Going to close this issue - I think we are in agreement that we need to limit the utility code we write, while keeping a focus on not taking dependencies for a few lines of code in some other library. In other words I think take what we absolutely need to make our library work. Then folks can use whatever they want outside that in their projects.
