### ISSUE TITLE
Bower distribution

### ISSUE THREAD

**Issue by patrick-rodgers** [OfficeDev/PnP-JS-Core#3]
Create and document a bower distribution package. Need to work with core team as Microsoft needs to "own" the package

**Comment by StfBauer** [comment]
Hi @patrick-rodgers,
I can take a look for the bower distribution stuff because I previously added a couple of things to bower.
The only thing that needs to be done by your team is to publish to bower.

**Comment by pr0peller** [comment]
Hi,
What is the status of this issue? I can research and try to help with this issue.

**Comment by patrick-rodgers** [comment]
It is a little on hold. We did some initial research and added the bower.json file, but I haven't actually created the package yet.

**Comment by pr0peller** [comment]
Ok. I'll see something else then. Thanks.

**Comment by patrick-rodgers** [comment]
This is completed and you can install the package via bower using

`bower install sp-pnp-js`
