### ISSUE TITLE
Latest merge removed all tests from build

### ISSUE THREAD

**Issue by pbjorklund** [OfficeDev/PnP-JS-Core#33]
Removing

```
    src.push("!src/*.test.ts");
    src.push("!src/**/*.test.ts");
```

from the build-typings task makes the tests actually compile again.

Should be fixed.

**Comment by patrick-rodgers** [comment]
Yes, actually caught this as well. Was so focused on getting the packaging work that I missed that I broke tests. Working on a fix now, deciding what to do. I don't necessarily want to include the tests in the lib for the npm package so might have a separate build folder and lib folder is just for packaging. Thanks for catching this.

**Comment by patrick-rodgers** [comment]
Should be fixed now, please have a look and confirm that "gulp test" works with latest dev branch.

**Comment by pbjorklund** [comment]
Yes @patrick-rodgers, test are running again :)

**Comment by patrick-rodgers** [comment]
Thanks for confirming, closing the issue.
