### ISSUE TITLE
ISSUE: No $pnp or pnp global object when using in Visual Studio (not Visual Studio Code)

### ISSUE THREAD

**Issue by alex-randall** [OfficeDev/PnP-JS-Core#36]
Update:

**_This may wider that just Visual Studio 2015... maybe issue with generated TypeScript definition file itself? It was reported on 4/28/2016 that the modern style of including the pnp.d.ts into a file doesn't work?  Need people to help figure this out, repro and also come up with a solution asap for all of us to review!_**

Has anyone attempted to use our TypeScript definition "pnp.d.ts" in a Visual Studio 2015 Professional/Enterprise (with Update 2) project yet (project type doesn't matter)?

I know right know we are targeting Visual Studio Code for at least contributions and also end user usage, however, for those of us that are used to Visual Studio 2015 Professional/Enterprise, it would be really cool to get the TypeScript definition pnp.d.ts to work there too!

The actual problem I'm experience is that I'm having major issues trying to get intellisense to work from another .ts file in the same project.

The usual:
`/// <reference path="pnp.d.ts" />`
references correctly (path is correct), but the $pnp object doesn't even exist from an intellisense point of view

Also I tried some of the "newer" ways to reference
`imports {$pnp} from "pnp" `
and while I get the $pnp object, it has no members in intellisense.  Admittedly I am a super newbie to this style of referencing so I could have the syntax completely wrong or it shouldn't even be referenced this way.

I tried to keep things simple in that I have the pnp.d.ts file in the same directory as the test.ts file.

On another note, I successfully referenced the pnp.js file from another JavaScript file using the
`/// <reference path="pnp.js" />`
syntax and the $pnp object exists and has full members present. 

So, from a TypeScript point of view and Visual Studio 2015 Professional/Enterprise (with Update 2) project:

1) Do I have the syntax wrong?
2) Is something else wrong?
        (default Visual Studio project file TypeScript compilation settings?)
3) Is it a legit issue with the TypeScript definition itself?

Would love to see if someone can repro this issue as well.

Thanks!

**Comment by patrick-rodgers** [comment]
This syntax works for me:

```
/// <reference path="pnp.d.ts" />
import PnP = require("pnp");
```
The first line gives the ref to the typings file and the second is the actual "import" into your code.

**Comment by alex-randall** [comment]
Thanks Patrick, will try and report back.

**Comment by patrick-rodgers** [comment]
So it looks to me that we would have to produce a set of es6 *.js files in the lib package and then have a separate build path for the pnp.js file that produces UMD. I guess I'll take a look at this one, which puts samples on the back burner unfortunately.

**Comment by alex-randall** [comment]
Cool thanks @patrick-rodgers. Sounds like that might handle the es6 side of things.  We'll see how it goes.

Maybe related questions:

1) I could be wrong, but doesn't the `import PnP = require("pnp"); ` syntax requires a (typing and runtime) dependency on requirejs?  I thought we didn't have any dependencies (at runtime) other than things that SharePoint itself provides on a SharePoint page?

2) Also shouldn't the naming of $pnp in something like: `import {$pnp} = from 'whateverwenameit';`
be used in all TypeScript documentation/samples instead since that's what is the global name ends up being in JavaScript?  Reason being: it make samples and documentation much easier to write for both TypeScript and JavaScript because the same $pnp variable can be referenced from whatever way you are including it.  Otherwise, the JavaScript and TypeScript samples and documentation will deviate radically with different "root variables" (PnP, $pnp).  Thoughts?

**Comment by patrick-rodgers** [comment]
Updated in #75, now supports:

import pnp from "sp-pnp-js";

**Comment by mike-morrison** [comment]
@patrick-rodgers New package is not working in jspm (and I suspect npm as well since jspm is simply downloading the npm package).

Here is the top of pnp.js that was downloaded from the 0.10 (confirmed in package.json) npm package.  

It doesn't look like it got transpiled to ES5

````
/* */ 
"format cjs";
"use strict";
import * as Util from "./utils/Util";
import { SharePoint } from "./SharePoint/SharePoint";
import { PnPClientStorage } from "./utils/Storage";
import * as Configuration from "./configuration/configuration";
import { Logger } from "./utils/logging";
import { Rest } from "./SharePoint/Rest/rest";
````

**Comment by mike-morrison** [comment]
Forgot to mention, Intellisense was working out of the box this time though.

**Comment by patrick-rodgers** [comment]
The code in /lib is es6 to support the es6 syntax. The code in the dist folder is es5 in a umd module and should be used in the browser.

**Comment by patrick-rodgers** [comment]
package updated to maintain the default export we desire for umd modules in the browser in #80. @alex-randall please test, would like to get this one closed.

**Comment by pr0peller** [comment]
Hi,
I just want to say that I test the library in ASP.Net application:

`///<reference path="../node_modules/sp-pnp-js/dist/pnp.d.ts"/>`
`import * as Pnp from "pnp";`
works,

`///<reference path="../node_modules/sp-pnp-js/dist/pnp.d.ts"/>`
`import Pnp = require("pnp");`
works also.
I have tested it also in Nodejs typescript application and it works the same way.
Dev env: Visual Studio 2015 Enterprise Update 2
Would be great if somebody else confirm the results.

**Comment by patrick-rodgers** [comment]
This appears to be fixed, thanks all.
