### ISSUE TITLE
Should the mock classes be refactored out of main library?

### ISSUE THREAD

**Issue by alex-randall** [OfficeDev/PnP-JS-Core#37]
Should the mock classes 

MockConfigurationProvider
MockLocation
MockStorage

not be a part of the final compiled pnp.d.ts, pnp.js and pnp.min.js?

Reasons:
- end users wouldn't not really use these directly in a SharePoint Page as they are for unit testing only...
- having them in the main pnp.js library adds additional bits and overhead to the library to not only download them to the browser, but also execute them at runtime (even when they are not used by the end user).  Yes agreed it's tiny, but it all adds up especially on slow connections/mobile devices.
- if end users really want to use these directly, perhaps they could be compiled into separate pnp.mocks.d.ts, pnp.mocks.js pnp.mocks.min.js libraries instead as it a very special use case (unit testing only)

Maybe too long term, but just thinking about keeping the main library as small as possible so it performs as fast as possible for end users.

Any thoughts?

**Comment by pbjorklund** [comment]
I don't think this is "small", it's a very valid point. Anything purely related to tests should not be part of the dist. @patrick-rodgers has started the work on moving tests out from the old structure where each .ts file had a matching tests.ts file. See the sharepoint/rest/tests folder.

What about using the same structure as https://github.com/Microsoft/TypeScript with a separate /test folder under the root of the library?

I would volunteer to make sure that all tests are moved to /tests and that for instance gulp is updated to work against that structure.

**Comment by patrick-rodgers** [comment]
This is something we talked about in early days and folks felt like having the .test.ts file along side the .ts file made it clearer and more obvious. At the time I agreed, but now that we have already grown and will continue to grow I am leaning towards moving to a separate test folder. I think it would be cleaner and reduce the "clutter" in the src folders. If you want to commit to moving things and updating the associated test gulp tasks that would be great, @pbjorklund .

**Comment by pbjorklund** [comment]
#62 handles this.

**Comment by patrick-rodgers** [comment]
Closing this as it was indeed resolved by #62. Great work by @pbjorklund on this.
