### ISSUE TITLE
Gulp Packaging

### ISSUE THREAD

**Issue by patrick-rodgers** [OfficeDev/PnP-JS-Core#4]
Need to create decide on and create a clean build/package process for the "dist" folder. This will be used potentially by various packages so need to address minification and module design.

**Comment by StfBauer** [comment]
I can take a look into this as well, if you like.

**Comment by patrick-rodgers** [comment]
That would be great - can discuss on this weeks call as well.

**Comment by pbjorklund** [comment]
What's wrong with the current ```package``` gulp task? Seems to do the job? :)

**Comment by patrick-rodgers** [comment]
Yes, I think we are OK here for now. This issue was created before I checked in the latest package script updates. We will continue to evolve, but I'll go ahead and close this issue. We can reopen if needed.
