### ISSUE TITLE
Gracefully fail gulp task when settings.js missing

### ISSUE THREAD

**Issue by tobiaswest83** [OfficeDev/PnP-JS-Core#41]
Happy to pick this up, logging in order to prevent duplication of effort

1) update the getting started guide to include a step for creating your settings.js for spsave
2) Update gulpfile.js in order to gracefully fail and signpost users to the getting started for how to create the settings file. 

@patrick-rodgers  - let me know if you're happy for me to proceed - you may not want the gulpfile.js altering?

**Comment by alex-randall** [comment]
Speaking of parallel tasks... I am experimenting now with breaking the gulpfile.js out into separate files because it's starting to get large (especially for the future documentation generation task)...

**Comment by tobiaswest83** [comment]
I think it's a great idea, gulp can very quickly become unmanageable. It will allow newcomers to gulp to get to grips with it too. Makes sense for it to be a separate issue as how we structure it is debate in itself!

**Comment by alex-randall** [comment]
Done https://github.com/OfficeDev/PnP-JS-Core/issues/43 

I will prioritize with me fixing that first (1-2 days as I've already started the work) so you can have the updates asap so you can do this fix you are proposing.  (I think it's a great idea!)

**Comment by tobiaswest83** [comment]
Created PR #44 for this

**Comment by tobiaswest83** [comment]
@alex-randall, looks like you made the appropriate changes in #47 for handling settings.js so this is perhaps redundant now?

**Comment by patrick-rodgers** [comment]
Closing this as the fix was made in the referenced PR. Thanks!
