### ISSUE TITLE
Break gulpfile.js into separate files under a buildtasks sub directory

### ISSUE THREAD

**Issue by alex-randall** [OfficeDev/PnP-JS-Core#43]
Patrick - Please assign me (alex-randall) this task as I am actively working on it and will have a pull request soon with it (1-2 days).

Background:
Gulpfile.js is starting to get large, but also anticipate much more growth in the future (such as for autogeneration of documentation).

Talked with Patrick about this offline.

I've already started work on breaking it apart and putting each task in a new "buildtasks" sub directory.  I will prioritize this work as high priority (meaning pull request created in 1-2 days so that:

- It can be reviewed/tested by others  asap (I will test it extensively of course in Visual Studio Code/gulp)
- After that, others can:
    - make other edits to the code to improve it, such as: (https://github.com/OfficeDev/PnP-JS-Core/issues/41)
    - add new functionality to it, such as: (https://github.com/OfficeDev/PnP-JS-Core/issues/6), which I am taking on for now

**Comment by alex-randall** [comment]
This work has completed and I have submitted it in pull request https://github.com/OfficeDev/PnP-JS-Core/pull/47

**Comment by patrick-rodgers** [comment]
Closing issue as it was resolved with PR. Thanks!
