### ISSUE TITLE
Quick Start Guide and settings.js

### ISSUE THREAD

**Issue by sympmarc** [OfficeDev/PnP-JS-Core#45]
This is definitely a dumb one. When I follow the Quick Start Guide and run gulp serve, I get the following error:

> module.js:341
> throw err;
> ^
> 
> Error: Cannot find module './settings.js'
> at Function.Module._resolveFilename (module.js:339:15)
> at Function.Module._load (module.js:290:25)
> at Module.require (module.js:367:17)
> at require (internal/module.js:16:19)
> at Object.<anonymous> (D:\WebstormProjects\OfficeDev\PnP-JS-Core\gulpfile.js:26:16)
> at Module._compile (module.js:413:34)
> at Object.Module._extensions..js (module.js:422:10)
> at Module.load (module.js:357:32)
> at Function.Module._load (module.js:314:12)
> at Module.require (module.js:367:17)

Looks like I need to create a settings.js file, probably from settings.example.js. There's nothing in the Quick Start Guide that describes that step, and there probably should be.

**Comment by alex-randall** [comment]
Thanks for the pull request to make the documentation better!  :)

**Comment by alex-randall** [comment]
Patrik, I just submitted a pull request that fixes this too as part of the breaking apart of the gulpfile.js into smaller chunks: https://github.com/OfficeDev/PnP-JS-Core/pull/47

**Comment by pbjorklund** [comment]
The best problem is a problem that someone else solves for you :)

**Comment by patrick-rodgers** [comment]
Closing this as it was fixed in a PR.
