### ISSUE TITLE
Developer Dashboard

### ISSUE THREAD

**Issue by patrick-rodgers** [OfficeDev/PnP-JS-Core#5]
Create a developer dashboard based on [the example ](https://github.com/OfficeDev/PnP/blob/master/Samples/Core.JavaScript/Core.JavaScript.CDN/js/pnp-devdashboard.js) from the first core library.

**Comment by alex-randall** [comment]
Hi Patrick, you'll have to let us know what kind of help wanted you were looking for on this... some enhancements, future directions, immediately need?  What exactly?  Thanks!

**Comment by patrick-rodgers** [comment]
This is likely not an immediate need. Also, based on the recent thinking around not including any DOM manipulation within the core library this would likely become an external module that uses the library (by subscribing to the logging API). I do want to keep it listed as I think there will be value in having the dev dashboard.

**Comment by alex-randall** [comment]
Yep agreed.  Thanks!
