### ISSUE TITLE
Code out files and folders REST API

### ISSUE THREAD

**Issue by patrick-rodgers** [OfficeDev/PnP-JS-Core#54]
Expand the existing files and folders classes to support all methods as outlined [here ](https://msdn.microsoft.com/en-us/library/office/dn450841.aspx).

**Comment by derek-smith** [comment]
Here I am :)

**Comment by patrick-rodgers** [comment]
All set, you're assigned. Thanks!

**Comment by derek-smith** [comment]
Thank you sir. I'm very excited to contribute!

**Comment by patrick-rodgers** [comment]
How's the work on this going? Any questions or blockers?

**Comment by derek-smith** [comment]
Planning on pushing the unit tests as soon as the gulp problem is fixed on the dev branch. Note that a lot of the methods are untested against SP. I just didn't find the time. I don't know, is that a blocker?

**Comment by patrick-rodgers** [comment]
Closing based on PR.
