### ISSUE TITLE
Code out Users, Groups, and Roles REST API

### ISSUE THREAD

**Issue by patrick-rodgers** [OfficeDev/PnP-JS-Core#55]
Code out the users, groups and roles REST API as outlined [here](https://msdn.microsoft.com/en-us/library/office/dn531432.aspx).

**Comment by patrick-rodgers** [comment]
How's the work on this going? Any questions or blockers?

**Comment by mike-morrison** [comment]
It's going well, I should have a PR today or tomorrow.  No questions or blockers at this point.  Thanks for asking.

**Comment by mike-morrison** [comment]
PR imminent.  My in-laws showed up early for my wedding so I lost a day.

**Comment by pr0peller** [comment]
Hi, can I help with something?

**Comment by mike-morrison** [comment]
@pr0peller I should be all set after I talk to @tobiaswest83 Friday afternoon (today).  I apologize again for the delay.  I ended up having to go to the ER yesterday, and the doc put me on bed rest for a couple of days.  I figure 1 day is enough.

**Comment by patrick-rodgers** [comment]
Closed by #118
