### ISSUE TITLE
Code out Search REST API surface

### ISSUE THREAD

**Issue by patrick-rodgers** [OfficeDev/PnP-JS-Core#59]
[Here is a start](https://msdn.microsoft.com/en-us/library/office/jj163876.aspx) for documentation. Lots of cool possibilities here, can probably hang it off Web or Site (or both).

**Comment by tobiaswest83** [comment]
Happy to look at this one if you like

**Comment by patrick-rodgers** [comment]
Great, it's all yours!

**Comment by sympmarc** [comment]
If it's at all useful from a comparison perspective, this is what I did for the SOAP Services in SPServices: https://spservices.codeplex.com/documentation

IMO, it's important that the examples actually DO something - and not something that no human would ever want to do.

There has to be a good index that gets people to the right place in a couple of clicks, and not only by using Google.

And any place where there's an assumption of prior knowledge should link back to that atomic building step.

There, my $.03.

**Comment by tobiaswest83** [comment]
Thanks a lot @sympmarc. 

There's a great discussion in #6 about automatic document generation using JSDOC and i assume we're using jsdoc comment notation @patrick-rodgers?

**Comment by patrick-rodgers** [comment]
Closing due to work in #70.
