### ISSUE TITLE
My wish list

### ISSUE THREAD

**Issue by mike-morrison** [OfficeDev/PnP-JS-Core#61]
## Feature wish list from putting on my JavaScript/Office developer hat.

`Disclaimer: This is just food for thought.  I just rambled out some features "I" would love to use assuming infinite resources.  A lot of these might be more appropriate to be a project built on top of this project or not at all.`

### **Things I like in other projects**
- The project would have a snappy one liner or a mission statement easy to remember.
- Supports Office/SharePoint 2013, 2016 on premises.  All Office 365 APIs.  
- Doesn't bring any C# baggage.
- Should be designed for modern JavaScript developers.  Not c# people.  <--- TypeScript is solving that problem already.  
- An API that feels simple, doesn't ask me for the same information repeatedly, etc.
- Feels fun and productive whether I am trying to use it in TS -> ES6 -> ES5
- Best in class support when writing code in VSCode, Visual Studio, WebStorm, Atom, etc.
- Best in class support when bundling with Webpack, Browserify, SystemJS
- Works great with Windows 10 UWP, Redux, React, React Native, Flux, JSX, Angular 1, Angular 2, Aurelia, and Electron.
- Great *"ready to start coding"* boilerplates for TS and ES2015.
- Inline code examples in the documentation

### **Things I want in my SP JS Dev life**
- Doesn't make REST easier.  Makes Office/SharePoint development in TypeScript/JavaScript easier.
  - Handles etags, I just get an ItemUpdatedOnServer exception and let me specify how to handle it.
  - Abstracts stuff like `_x0020_`.
  - Never returns me crazy search api results like row[30].column[5] unless I requested them.
  - Always offers the raw results next to the pretty results.
  - Simplifies paging through large lists of users, items, and getting counts.  Has example demonstrating.
  - Minimizes the developer having to pass GUIDs or having to lookup the value to a parameter in SharePoint.
  - If you give me back something that has a user/expandable property associated, expand it for me or make it simple.  `{ expandoAutoExpand: true }`
  - Makes authenticating easy.  Whether it is school or org, domain, on premises, cloud, etc.  
    - Most SP libraries punt this off to the developer!  
    - IMO this is still a big barrier to entry in the current spdev (javascript) landscape.  
  - It will only load the minimum code required to perform it's function. a.k.a. fast everywhere. Including dependencies. i.e. [Rollup](https://github.com/rollup/rollup)  
- Focus on great simple developer outcomes, not wrapping every api.  Eventually wrap the entire API.
- Stability is critical.  
- Sample projects for the popular libraries/frameworks. Maybe a [Todo MVC](http://todomvc.com) on top of the SP task list?
- Great getting started tutorial.
- Great documentation that accepts contributions from the community.
- Great readme with some of those video screenshots everyone is using showing off some of the best developer friendly features.
- I would really love it if a library could do all of its heavy work with a queue of web workers (if supported in browser) for performance and freeing up the UI thread.
  - Speaking of heavy work, a library should assume that everyone that uses this library is using it against a large list/search index/user info table.  It needs to scale.
- Make the basics awesome, webs, lists, users, doc libs, files, etc.  
  - SPServices is a great example of this.  Many times I have seen end users with 3 - 5 line snippets of SPServices on the page.  When business people are using your api, because it looks simple to them.  That is epic.  
- Makes it easy to integrate via webpart for power users.
- Makes custom forms in SharePoint easier.
- Great offline support in Windows 10, Xamarin, browsers, etc. 
  - IndexedDb, Sqlite, etc.

### **React and friends**

In my opinion React, React Native, Redux/Flux, are going to continue to snowball and get even bigger.  They make development easier.  That is always a **huge** hit with developers.
- React components with Material Design, Office Fabric, and/or WinJS baked in.
- Make it dead simple to piece these react/web components together to make simple add-in apps for Office Suite, add-in parts for SharePoint, etc.  Code like `<PeoplePicker scope=site ... />`.  <---That looks sexy.

**Comment by sympmarc** [comment]
It was a great list, though!

**Comment by dzearing** [comment]
+1

**Comment by mike-morrison** [comment]
Sorry for taking it down.

**Comment by tobiaswest83** [comment]
@mike-morrison, lots of cool ideas in here - I'm building the search APi at the moment & will certainly take on board what you said regarding the response data, since it's quite unfriendly by default. 

### React

At the moment, the library is, I believe looking to be agnostic of technology as it builds the core services. As focus shifts once the v1 milestone has been reached, I'm almost certain

Finally, regarding React Fabric components, not sure that would be the intention at least in this SIG, there's already a separate Angular 1 project for Fabric over at [ngOfficeUIFabric](https://github.com/ngOfficeUIFabric/ng-officeuifabric). 

These are just my thoughts of course, @patrick-rodgers is doing a great job of heading this up nd may be able to provide more input.

**Comment by mike-morrison** [comment]
@tobiaswest83 I agree.  The React Fabric components in my head are in a project built using this project.  At most in this project it would just be as a technology specific quick start or example.  

IMO, PnP *should* be as technology agnostic as possible.

That Angular 1 project is pretty much what I would love to have except with React.

**Comment by SPDoctor** [comment]
Got to say I am a bit of a fan of React as well, but I think this project should be at a lower level in the stack. This was one of the problems I had with the original version of the ADAL.js library - it was intertwined with Angular 1, which is great if you happen to be using Angular 1. If you just want to figure out the five lines of code you need to get a token and you happen not to be a regular user of Angular then you are going to have to find those five lines embedded and scattered around an unfamiliar framework. They fixed that by separating into two libraries, but I think it is better to start off separate - then maybe have sample code using Angular 1,2, React, etc. Same with Fabric.

**Comment by sympmarc** [comment]
+100 to @SPDoctor. Frameworks are great when you're at the UI level, but this library should be as basic as it can be to get the job done.

**Comment by patrick-rodgers** [comment]
This is a great conversation and want to keep it going - so have moved it to a [Yammer Thread](https://www.yammer.com/itpronetwork/#/Threads/show?threadId=700774408).

The reason being this isn't an issue we can close/resolve. Fantastic list and want to keep these things in mind for sure.
