### ISSUE TITLE
LocaleID enumeration

### ISSUE THREAD

**Issue by tobiaswest83** [OfficeDev/PnP-JS-Core#64]
Should we implement a LocaleID enumeration, based on the table [here](https://msdn.microsoft.com/en-us/goglobal/bb964664.aspx)?

It's used in quite a number of place and I for one am forever having to keep coming back to that table during my working hours.

**Comment by patrick-rodgers** [comment]
We could, though I don't think it is necessary. Just providing the ability to pass a number is sufficient to me.

**Comment by tobiaswest83** [comment]
OK great, I'll close this now then.

**Comment by pbjorklund** [comment]
Why not just create an enum for it? Should work fine (at least from what I gather from https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#9 and the test below)

Test
``` describe("enums", () => {
        it("is interchangable with number", () => {
            let result: number = sut.enumTakingFunc(Locale.Finglish);
            assert.equal(result, Locale.Finglish);
        });
    });
```

Partial implementation
```
enum Locale {
    "Afrikaans - South Africa" = 1078,
    "Swedish" = 1053,
    "Finglish" = 1337
}

enumTakingFunc(val: number) {
        return val;
    }
```

**Comment by patrick-rodgers** [comment]
Yes, an enum is all we need for this. If someone wants to add it, that's fine with me.

**Comment by tobiaswest83** [comment]
That's what I was planning to do, I'll implement it as part of the search PR, feel free to assign this to me

**Comment by pbjorklund** [comment]
#67

**Comment by patrick-rodgers** [comment]
This was done and merged into dev - so closing issue. Thanks @pbjorklund and @tobiaswest83.
