### ISSUE TITLE
utils/logging.ts - require() should be changed?

### ISSUE THREAD

**Issue by alex-randall** [OfficeDev/PnP-JS-Core#72]
In working on the [documentation generation](https://github.com/OfficeDev/PnP-JS-Core/issues/6), I noticed that in utils/logging.ts, there is a line near the top that is:
`import Collections = require("../collections/Collections");`

This one time occurrence is actually output in the pnp.d.ts TypeScript definition file.

Shouldn't that be changed instead to something like
`import { Collections } from "../collections/Collections";`
to use the es6 pattern that is used everywhere else in the codebase?  That way code generation will go easier and perhaps reduce runtime dependency on requirejs (if that's what this is doing)?

**Comment by mike-morrison** [comment]
I say make it consistent.

**Comment by patrick-rodgers** [comment]
Fixed in #75
