### ISSUE TITLE
Allow CAML queryies to be executed against lists

### ISSUE THREAD

**Issue by russgove** [OfficeDev/PnP-JS-Core#91]
We need to be able to execute CAML queries wen oob rest does not meet our needs. Add a method getCAML to the list object that takes a CAML Query. How Do II assign this to myself?

**Comment by patrick-rodgers** [comment]
You can't assign yourself until I add you as a contributor. Done, and you are assigned. Thanks!

**Comment by russgove** [comment]
Heym I didnt know it was already there.
